# (PART) Basic water balance modelling {-}

# Basic water balance model {#basicwaterbalance}

This chapter provides an overview of the basic soil and plant water balance model included in **medfate**. The model allows simulating vertical water fluxes in a forest stand, and performs soil and plant water balance on a daily step basis for the period corresponding to input weather data. 

The model is run using function `spwb()`, for a set of days, or function `spwb_day()`, for a single day. Alternatively, one can use function `pwb()` to evaluate plant transpiration and drought stress resulting from given weather and soil moisture dynamics. The basic water balance model corresponds to the control variable `transpirationMode = "Granier"`.

The description of the model presented here conforms to a large extent to the description given in @DeCaceres2015, but includes several modifications that have been implemented since the publication of this scientific article. The information provided in this chapter should be enough to understand what the model does and when it can be useful, but the reading the following ones should provide a more detailed understanding on how the different processes are formulated.

## Design principles {#basicdesign}

The water balance model considers only the vertical spatial dimension of the stand and not the horizontal distribution of plants within it. In other words, the model is not spatially explicit (i.e., plants do not have horizontal coordinates nor interact for space explicitly). Woody vegetation in the stand is divided into groups, here referred to as *plant cohorts* of different species, height and leaf area index ($LAI$). Height and $LAI$ values determine competition for light. $LAI$ values also drive competition for soil water, along with fine root distribution. The model can also consider a layer herbaceous vegetation, which also has a height value and $LAI$, but where plant cohorts are not distinguished and with fine roots confined to the topmost layer. 

The soil water balance initially followed mostly the design principles of SIERRA [@Mouillot2001;@Ruffault2014;@Ruffault2013] and BILJOU [@Granier1999;-@Granier2007], although nowadays it has evolved substantially. Hydrological processes include rainfall interception loss [@Gash1995; @liu_evaluation_2001], plant transpiration, evaporation from bare soil [@Ritchie1972], snow melt, infiltration into the soil matrix [@Boughton1989; @green_studies_1911] and vertical water movement within the soil, the latter following MACRO [@jarvis_modelling_1991; @larsbo_improved_2005], a dual-permeability model where total porosity is partitioned into two separate flow regions (matrix and macropores), each with its own degree of saturation, conductivity and flow rate. Potential evapo-transpiration ($PET$) determines maximum herbaceous and maximum canopy transpiration ($Tr_{\max}$) using an empirical relationship between the $LAI$ of the stand and the ratio $Tr_{\max}/PET$ [@Granier1999]. Actual plant transpiration is estimated using a function that depends not only on $Tr_{\max}$ but also on current soil moisture levels, cohort-specific drought resistance, fine root distribution and the degree of shading of the target plant cohort. When soil water deficit progresses, transpiration rates are consequently reduced, but minimum transpiration rates of woody vegetation are not zero, because of the role of cuticular transpiration and imperfectly closed stomata [@Duursma2018]. Woody plant water status (i.e. plant water potential and, hence, plant water content) follows variations of soil moisture in the soil layers where fine roots are located. 

By default, the model assumes that soil moisture under all plant cohorts is the same (i.e. water sources corresponding to vertical soil layers are shared among cohorts). However, 3D variations in soil moisture beneath plant cohorts can be simulated in spatially-explicit forest ecosystem models [@Manoli2017; @Rotzer2017]. The water balance model does not simulate horizontal spatial processes explicitly, but allows considering more or less independent water pools for plant cohorts. If partial or completely independent water pools are considered, hydrological processes are replicated for the fraction of soil corresponding to each woody cohort. Transpiration of each plant cohort depends on the soil moisture beneath itself and, depending on the degree of rhizosphere overlap, on the soil moisture beneath other plant cohorts.

## State variables {#statevariablesbasic}

The following are state variables in the model under all simulations:

+ Cumulative degree days (a) to budburst, (b) to complete unfolding or (c) to senescence ($S_{eco,d}$, $S_{unf,d}$ or $S_{sen,d}$; all in $^\circ C$), are tracked by the model to determine leaf phenological status (see \@ref(leafphenology)).
+ Soil moisture content dynamics on each layer $s$ are tracked daily using $W_s = \theta_s(\Psi)/ \theta_{fc,s}$, the *proportion of soil moisture in relation to field capacity*, where moisture at field capacity, $\theta_{fc,s}$, is assumed to correspond to $\Psi_{fc} = -0.033$ MPa. Note that $W_s$ values larger than one are possible if the soil is between field capacity and saturation (which can happen if deep drainage is not allowed).
+ Plant water potential ($\Psi_{plant,i}$) of each plant cohort $i$ are also tracked daily and follows the soil water potential of layers (or water pools) where fine roots are located.

Additional state variables depend on the activation of specific control flags:

+ *If snow accumulation/melting is considered*, the model tracks $S_{snow}$, the snow water equivalent (in mm) of the snow pack storage over the surface.
+ *If stem cavitation is not completely reversible*, the model tracks $PLC_{stem, i}$ and $PLC_{leaf, i}$, the proportion of conductivity lost the stem and leaves, respectively, of plants of cohort $i$.
+ *If the degree of rhizosphere overlap between plant cohorts is not total* (i.e. if `rhizosphereOverlap = "none"` or `rhizosphereOverlap = "partial"`), the model also tracks $W_{i,s}$, the proportion of soil moisture in relation to field capacity for layer $s$ within the areal fraction of the stand covered by the woody cohort $i$.

## Water balance {#soilwaterbalance}

Water balance is performed for both the snow pack and the soil. Precipitation ($P$) is considered be snow precipitation ($Ps$) or rainfall ($Pr$), depending on temperature. Thus, we have:
\begin{equation}
P = Pr + Ps
\end{equation}

The water balance of the snow pack ($\Delta{S_{snow}}$ in mm of snow water equivalents) is simply defined as:
\begin{equation}
\Delta{S_{snow}} = Ps - Sm
(\#eq:snowbalanceequation)
\end{equation}
where $Ps$ is precipitation as snowfall and $Sm$ is snow melt. Interception on canopy surfaces is only modelled for liquid precipitation, which leads to a partioning of $Pr$ into interception loss ($In$; i.e. water evaporated after being intercepted by the canopy surfaces) and net rainfall ($Pr_{net}$; the sum of throughfall and stem flow): 
\begin{equation}
Pr = Pr_{net} + In
\end{equation}
Several water sources can contribute to soil infiltration, namely net rainfall ($Pr_{net}$), surface runon from nearby locations ($Ro$, if provided) and snowmelt ($Sm$). Given that not all water that reaches the soil surface actually infiltrates, the amount of water entering the first soil layer via infiltration ($If$) is:
\begin{equation}
If = Pr_{net} + Sm + Ro - Ie
(\#eq:infiltrationequation)
\end{equation}
where $Ie$ is the infiltration excess that may occur. Other water inputs into the soil can come via capillarity rise ($Cr$) from the water table (if present) or via lateral interflow from nearby locations ($Lw$; if provided, assumed positive in the direction of entering the local soil). There are multiple ways water can leave the soil. Regarding purely physical processes we have the evaporation from soil surface ($Es$), saturation excess ($Se$) and deep drainage ($Dd$). Fluxes mediated by plants are the transpiration made by herbaceous plants ($Tr_{herb}$) and the transpiration made by woody plants ($Tr_{woody}$). Taking all input and output terms, daily variations in soil water content ($\Delta{V_{soil}}$ in mm) are then summarized as:
\begin{equation}
\Delta{V_{soil}} = (If + Lw + Cr) - (Dd + Se + Es + Tr_{herb} + Tr_{woody})
(\#eq:basicwaterbalanceequation)
\end{equation}
The water leaving the soil via surface runoff ($Ru$) is defined as the sum of infiltration excess ($Ie$) and saturation excess ($Se$):
\begin{equation}
Ru = Ie + Se
(\#eq:runoffequation)
\end{equation}

If we consider soil and snow pack altogether, the water balance of the whole forest becomes:
\begin{equation}
\Delta{V_{soil}} + \Delta{S_{snow}} = (P + Ro + Lw + Cr) - (Dd + Ru + In + Es + Tr_{herb} + Tr_{woody})
(\#eq:forestwaterbalanceequation)
\end{equation}
Among inputs, precipitation ($P$) will the most relevant inflow on most instances. The liquid water fluxes contributing to **blue water** outflow (i.e. entering river networks or leading to ground water) are runoff ($Ru$) and deep drainage ($Dd$). Water vapor fluxes ($Es$, $Tr_{woody}$, $Tr_{herb}$, $In$) contribute to total evapotranspiration, or **green water** (i.e. water vapor returning to the atmosphere).

While the above describes the default water balance equations, variations can occur depending on specific control flags: 

a. *If snow dynamics are considered* [`snowpack`], evaporation from bare soil cannot occur if there is a snow pack over the soil (i.e., if $S_{snow}>0$ then $Es = 0$).
b. *If plant water pools are considered* [`rhizosphereOverlap`], the soil water balance equation applies not only to the soil of the overall stand but also to the soil beneath each woody plant cohort. The fraction of stand area corresponding to the water pool of each cohort is used to keep the water balance at the two scales aligned. Moreover, the water balances of soils beneath the different plant cohort are more or less correlated depending on the degree of rhizosphere overlap.
c. *If soil flows are simulated using a dual-permeability domain* [`soilDomains`] there are water balance equations for the soil matrix and the macropore domain. Moreover, it affects the infiltration amounts (and hence runoff), in the latter including infiltration via macropores. 

## Process scheduling {#basicwaterbalancescheduling}

For every day to be simulated, the model performs the following steps:

  1. Update leaf area values according to the phenology of species and recalculate radiation extinction (sections \@ref(leafphenology) and \@ref(basiclightextinction)).
  2. Determine rainfall interception loss ($In$) and net rainfall ($Pr_{net}$) (section \@ref(interception)). The amount of water reaching the soil surface from the rainfall event is the sum of net rainfall ($Pr_{net}$) and surface runon ($Ro$), if given. If snow dynamics are included, increase snow pack from snow precipitation ($Ps$) and decrease it following snow melt ($Sm$) (section \@ref(snowpack)).
  3. Determine bare soil evaporation ($Es$), if snow is not present (section \@ref(soilevaporation)), and herbaceous transpiration ($Tr_{herb}$; section \@ref(herbaceoustranspiration)).
  4. Determine woody plant transpiration ($Tr_{woody}$), including hydraulic redistribution, and photosynthesis (chapter \@ref(transpirationgranier)). Update plant water potential ($\Psi_{plant}$) and plant drought stress for each plant cohort.
  5. Determine rainfall infiltration (section \@ref(infiltration)) and vertical water movement within the soil (section \@ref(soilflows)), while considering soil layer source/sinks from snow melt, bare soil evaporation and herbaceous transpiration and woody plant extraction/redistribution. This updates soil moisture and returns infiltration ($If$), runoff ($Ru$) and deep drainage ($Dd$). 
  6. If fire hazard calculations are requested, estimate live and dead fuel moisture and potential fire behaviour (chapter \@ref(fuelandfirebehavior)).

The set of steps corresponds to simulations if plant water pools *are not* considered, so that only the water balance of the overall soil matters. If plant water pools *are* considered, steps 1, 2 and 6 are the same, because they apply to the whole forest stand. However, steps 3 is performed for each water pool separately because it depends on antecedent soil moisture. Step 4 also involves defining woody plant water uptake from different plant water pools depending on the proportion of fine roots of each woody cohort in each pool (see \@ref(transpirationpools)). Step 5 is also performed on the soil corresponding to each pool, and the resulting infiltration, runoff and drainage estimates are averaged at the stand level. Finally, the soil moisture of the overall soil is estimated by averaging the soil moisture of water pools.

## Inputs and outputs {#basicwaterbalanceinputsoutputs}

### Soil, vegetation and meteorology

**Soil**

Soil input requirements are fully described in section \@ref(soilinput).

**Vegetation**

Vegetation input requirements are fully described in section \@ref(vegetationinput). Trees and shrubs do not need to be characterized with different variables in soil water balance calculations, since both kinds of woody cohorts have a $LAI$ value. In most cases, users only need to estimate the leaf area index corresponding to live leaves, i.e. $LAI^{live}$, because normally at the starting point all leaves are expanded (i.e. $LAI^{\phi} = LAI^{live}$) and one can assume no dead leaves in the canopy (i.e., $LAI^{dead} = 0$). Vegetation characteristics stay constant during simulations using function `spwb()`, although the actual expanded leaf area ($LAI^{\phi}$) and dead leaf area ($LAI^{dead}$) may vary is the species is winter deciduous.

**Meteorology**

The minimum weather variables required to run the model are min/max temperatures ($T_{min}$ and $T_{max}$), min/max relative humidity ($RH_{min}$ and $RH_{max}$), precipitation ($P$) and solar radiation ($Rad$). Wind speed ($u$) is also needed, but the user may use missing values if not available (a default value will be used in this case). Wind speed is assumed to have been measured at a specific height above the canopy (by default at 2 m). Atmospheric $CO_2$ concentration ($C_{atm}$) may also be specified, but if missing a default constant value is assumed, which is taken from the control parameters. Definitions and units of these variables were given in section \@ref(meteoinput).

### Vegetation functional parameters {#basicwatervegetationparameters}

The following sets of functional parameters should be supplied for each woody plant cohort. In practice, they are normally estimated from the species-specific parameter table and imputation of missing values (see \@ref(modelparametrization)). Functional attributes are filled for each cohort $i$ by function `forest2spwbInput()` from species identity (i.e. $SP_i$). However, different parameters can be specified for different cohorts of the same species if desired (see section \@ref(functionaltraits)). 

A first set of functional parameters refers to leaf phenology (`paramsPhenology`):

| Symbol | Units | R  | Description                                  | 
|--------|-------|----| ---------------------------------------------|
|        |       |  `PhenologyType`  | Leaf phenology type (oneflush-evergreen, progressive-evergreen, winter-deciduous, winter-semideciduous)|
| $LD$ | years  | `LeafDuration` | Average duration of leaves (in years). |
| $t_{0,eco}$ | days | `t0gdd` | Date to start the accumulation of degree days. |
| $S^*_{eco}$ | $^{\circ} \mathrm{C}$ | `Sgdd` | Degree days corresponding to leaf budburst (see section \@ref(leafphenobudburst)). |
| $T_{eco}$ | $^{\circ} \mathrm{C}$ | `Tbgdd` | Base temperature for the calculation of degree days to leaf budburst (see section \@ref(leafphenobudburst)). |
| $S^*_{sen}$ | $^{\circ} \mathrm{C}$ | `Ssen` | Degree days corresponding to leaf senescence (see section \@ref(leafphenosenescence)). |
| $Ph_{sen}$ | hours | `Phsen` | Photoperiod corresponding to start counting senescence degree-days (see section \@ref(leafphenosenescence)). |
| $T_{sen}$ | $^{\circ} \mathrm{C}$ | `Tbsen` | Base temperature for the calculation of degree days to leaf senescence (see section \@ref(leafphenosenescence)). |
| $x_{sen}$ | {0,1,2}  | `xsen` | Discrete values, to allow for any absent/proportional/more than proportional effects of temperature on senescence (see section \@ref(leafphenosenescence)). |
| $y_{sen}$ | {0,1,2}  | `ysen` | Discrete values, to allow for any absent/proportional/more than proportional effects of photoperiod on senescence (see section \@ref(leafphenosenescence)). |

A second set of parameters relate to light extinction and water interception (`paramsInterception`):

| Symbol | Units | R  | Description                                  | 
|--------|-------|----| ---------------------------------------------|
| $k_{PAR}$ | | `kPAR` | PAR extinction coefficient (see section \@ref(basiclightextinction)). |
| $s_{water}$ | $mm\,H_2O·LAI^{-1}$ | `g` | Crown water storage capacity (i.e. depth of water that can be retained by leaves and branches) per LAI unit (see section \@ref(interception)). |

A third set includes parameters related to plant anatomic and morphological attributes (`paramsAnatomy`):

| Symbol | Units | R param | Description                             |
|--------|-------|---------|-----------------------------------------|
| $1/H_{v}$  | $m^2 \cdot m^{-2}$ | `Al2As` | Ratio of leaf area to sapwood area |
| $RLR$  | $m^2 \cdot m^{-2}$ | `Ar2Al` | Fine root area to leaf area ratio |
| $SLA$  | $m^2 \cdot kg^{-1}$ | `SLA` | Specific leaf area |
| $\rho_{leaf}$ | $g \cdot cm^{-3}$ | `LeafDensity` | Leaf tissue density |
| $\rho_{wood}$ | $g \cdot cm^{-3}$ | `WoodDensity` | Wood tissue density |
| $\rho_{fineroot}$ | $g \cdot cm^{-3}$ | `FineRootDensity` | Fine root tissue density |
| $SRL$ | $cm \cdot g^{-1}$ | `SRL` | Specific root length |
| $RLD$ | $cm \cdot cm^{-3}$ | `RLD` | Fine root length density (i.e. density of root length per soil volume) |
| $r_{6.35}$ | | `r635` | Ratio between the weight of leaves plus branches and the weight of leaves alone for branches of 6.35 mm |


A fourth set of parameters are related to transpiration and photosynthesis (`paramsTranspiration`):

| Symbol | Units | R  | Description                                  | 
|--------|-------|----| ---------------------------------------------|
| $g_{swmin}$ | $mol\, H_2O \cdot s^{-1} \cdot m^{-2}$ | `Gwmin` | Minimum stomatal conductance to water vapour |
| $T_{max, LAI}$ |       | `Tmax_LAI` | Empirical coefficient relating LAI with the ratio of maximum transpiration over potential evapotranspiration (see section \@ref(maximumtranspiration)). |
| $T_{max, sqLAI}$ |       | `Tmax_LAIsq` | Empirical coefficient relating squared LAI with the ratio of maximum transpiration over potential evapotranspiration (see section \@ref(maximumtranspiration)). |
| $\Psi_{extract}$ | $MPa$ | `Psi_Extract` |  The water potential at which plant transpiration is 50% of its maximum (see section \@ref(actualtranspiration)).|
| $c_{extract}$ |  | `Exp_Extract` |  Parameter of the Weibull function regulating transpiration reduction (see section \@ref(actualtranspiration)).|
| $c_{leaf}$, $d_{leaf}$ | (unitless), MPa | `VCleaf_c`, `VCleaf_d` | Parameters of the vulnerability curve for leaf xylem |
| $c_{stem}$, $d_{stem}$ | (unitless), MPa | `VCstem_c`, `VCstem_d` | Parameters of the vulnerability curve for stem xylem |
| $WUE_{\max}$ | $g\, C \cdot mm^{-1}$ |  `WUE` |  Water use efficiency at VPD = 1kPa and without light or CO2 limitations (see section \@ref(basicphotosynthesis)).  |
| $WUE_{PAR}$ |  |  `WUE_par` |  Coefficient describing the progressive decay of WUE with lower light levels (see section \@ref(basicphotosynthesis)). |
| $WUE_{CO2}$ |  |  `WUE_co2` |  Coefficient for WUE dependency on atmospheric CO2 concentration \@ref(basicphotosynthesis)).  |
| $WUE_{VPD}$ |  |  `WUE_vpd` |  Coefficient for WUE dependency on vapor pressure deficit \@ref(basicphotosynthesis)).  |

A fifth (final) set of parameters are related to water storage and water relations in plant tissues (`paramsWaterStorage`):

| Symbol | Units | R  | Description                                  | 
|--------|-------|----| ---------------------------------------------|
| $LFMC_{\max}$ | % | `maxFMC` | Maximum live fuel moisture content, corresponding to fine fuels (< 6.35 mm twigs and leaves). |
| $\epsilon_{leaf}$ | MPa | `LeafEPS` | Modulus of elasticity of leaves |
| $\epsilon_{stem}$ | MPa | `StemEPS` | Modulus of elasticity of symplastic xylem tissue |
| $\pi_{0,leaf}$ | MPa | `LeafPI0` | Osmotic potential at full turgor of leaves |
| $\pi_{0,stem}$ | MPa | `StemPI0` | Osmotic potential at full turgor of symplastic xylem tissue |
| $f_{apo,leaf}$ | [0-1] | `LeafAF` | Apoplastic fraction in leaf tissues |
| $f_{apo,stem}$ | [0-1] | `StemAF` | Apoplastic fraction in stem tissues |
| $V_{leaf}$ | $l \cdot m^{-2}$ | `Vleaf` | Leaf water capacity per leaf area unit |
| $V_{sapwood}$ | $l \cdot m^{-2}$ | `Vsapwood` | Sapwood water capacity per leaf area unit |



### Control parameters  {#basicwaterbalancecontrol}

Control parameters modulate the overall behaviour of water balance simulations (see section \@ref(controlparameters)). Most importantly, `transpirationMode` defines the transpiration model, which in turn defines the complexity of the water balance model. If `transpirationMode = "Granier"` (the default value) then the basic water balance model is used. 

The other relevant control parameters for the basic water balance model are:

+ `soilFunctions [="SX"]`: Soil water retention curve and conductivity functions, either 'SX' (for Saxton) or 'VG' (for Van Genuchten). 
+ `defaultWindSpeed [= 2.5]`: Default value for wind speed (in $m \cdot s^{-1}$) when this is missing (only used for leaf fall, see section \@ref(leafphenology)).
+ `defaultCO2 [=386]`: Default atmospheric (abovecanopy) $CO_2$ concentration (in micromol $CO_2 \cdot mol^{-1}$ = ppm). This value will be used whenever $CO_2$ concentration is not specified in the weather input.
+ `defaultRainfallIntensityPerMonth [= c(1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 5.6, 5.6, 5.6, 5.6, 5.6, 1.5)]`: A vector of twelve values indicating the rainfall intensity (mm/h) per month. By default synoptic storms (1.5 mm/h) are assumed between December and June, and convective storms (5.6 mm/h) are assumed between July and November [@Miralles2010].
+ `snowpack [= TRUE]`:  Whether dynamics of snow pack are included (see section \@ref(snowpack)).
+ `leafPhenology [ = TRUE]`:  Whether leaf phenology is simulated (see section \@ref(leafphenology)). If `FALSE` then all species are assumed to be evergreen.
+ `bareSoilEvaporation [= TRUE]`:  Whether evaporation from the soil surface is simulated (see section \@ref(soilevaporation)).
+ `unlimitedSoilWater [=FALSE]`: Boolean flag to indicate the simulation of plant transpiration assuming that soil water is always at field capacity.
+ `unfoldingDD [= 300]`: Degree-days for complete leaf unfolding after budburst has occurred ($S_{unf}^*$; see section \@ref(leafphenobudburst)).
+ `interceptionMode [= "Gash1995"]`: Infiltration model, either "Gash1995" or "Liu2001"; see section \@ref(interception).
+ `infiltrationMode [= "GreenAmpt1911"]`: Infiltration model, either "GreenAmpt1911" or "Boughton1989"; see section \@ref(infiltration).
+ `soilDomains [= "single"]`: Either "single" (for single domain) or "dual" (for dual-permeability) (see section \@ref(soilflows)).
+ `fireHazardResults [= FALSE]`: Boolean flag to force calculation of daily fire hazard.
+ `rhizosphereOverlap [="total]`: A string indicating the degree of rhizosphere spatial overlap between plant cohorts:
   + `"none"` - no overlap (independent water pools).
   + `"partial"` - partial overlap determined by coarse root volume.
   + `"total"` - total overlap (plants extract from common soil pools).
+ `verticalLayerSize [= 100]`: Size of vertical layers (in cm) for the calculation of light extinction (see section \@ref(leafdistribution)).
+ `windMeasurementHeight [ = 200]`: Height (in cm) over the canopy corresponding to wind measurements.
+ `stemCavitationRecovery/leafCavitationRecovery [= "rate"]`: A string indicating how to model recovery of xylem conductance (see section \@ref(cavitationRecovery)). Allowed values are: 
  + `"none"` - no recovery.
  + `"annual"` - complete recovery every first day of the year.
  + `"total"` - instantaneous complete recovery.
  + `"rate"` - following a rate of new leaf or sapwood formation.

### Model output {#basicwaterbalanceoutput}

Functions `spwb()` and `pwb()` return a list of a class with the same name. The first four elements of this list (i.e., `latitude`, `topography`, `weather` and `spwbInput`) are simply copies of model inputs. The next element is `spwbOutput`, which contains the state of the input object at the end of the simulation (this can be used to perform further simulations starting with current values of state variables). The next five elements correspond to *water balance flows*, *soil state* variables, *stand-level* variables, *plant-level* and *fire hazard* results:

| Element | Description                                                |
|---------|------------------------------------------------------------|
| `WaterBalance`| Climatic input and water balance flows of eq.\@ref(eq:basicwaterbalanceequation) (i.e. net precipitation, infiltration, runoff, transpiration...). All of them in $mm = l \cdot m^{-2}$. |
| `Soil`| Soil variables for each soil layer: Moisture relative to field capacity ($W_s$), water potential ($\Psi_s$) and volumetric water content ($V_s$). |
| `Stand`| Stand-level variables, such as $LAI^{\phi}_{stand}$, $LAI^{dead}_{stand}$, the water retention capacity of the canopy ($S_{canopy}$) or the fraction of light reaching the ground ($L^{PAR}_{ground}$ and $L^{SWR}_{ground}$).|
| `Plants`| Variables defined at the level of woody plant cohort, such as expanded leaf area ($LAI^{phi}_i$), transpiration, photosynthesis, water potential, etc. |
| `FireHazard`| Fire hazard variables (fuel moisture, rate of spread, fire potentials, etc). Only returned if `fireHazardResults = TRUE`. |

Elements `WaterBalance`, `Soil`, `Stand` and `FireHazard` are data frames with dates in rows and variables in columns, whereas `Plants` is itself a list with several data frames, with dates in rows and woody plant cohorts in columns:

| Element | Symbol | Units | Description                               |
|---------|--------|-------|-------------------------------------------|
|`LAI`| $LAI^{\phi}$ | $m^2 \cdot m^{-2}$ | Leaf area index (expanded).|
|`LAIlive`| $LAI^{live}$ | $m^2 \cdot m^{-2}$ | Leaf area index (live).|
|`AbsorbedSWRFraction` | $f_i$ | [0-1] | Fraction of shortwave radiation absorbed.|
|`Transpiration`| $Tr$ | mm | Transpiration per unit ground area.|
|`GrossPhotosynthesis`| $A_{g}$ | $g\,C \cdot m^{-2}$ | Gross photosynthesis per unit ground area.|
|`PlantPsi` | $\Psi_{plant}$ | $MPa$ | Plant water potential.|
|`LeafPLC` | $PLC_{leaf}$ | [0-1] | Degree of leaf embolisation.|
|`StemPLC` | $PLC_{stem}$ | [0-1] | Degree of stem embolisation.|
| `PlantWaterBalance` | | mm | Internal daily plant water balance (balance of soil extraction and transpiration). |
| `LeafRWC`| $RWC_{leaf}$ | % | Mean leaf relative water content. |
| `StemRWC`| $RWC_{stem}$ | % | Mean stem relative water content. |
| `LFMC`| $LFMC$ | % | Live fuel moisture content (as percent of dry weight), corresponding to fine fuels (< 6.35 mm twigs and leaves). |
|`PlantStress` | $DDS$ | [0-1] | Drought stress level suffered by each plant cohort (relative whole-plant transpiration).|

The output of simulations can be inspected using `plot`, `shinyplot` and `summary` functions specific to `spwb` objects (examples are given in the corresponding package *vignette*).

As it simulates water balance for only one day, function `spwb_day()` returns a much more reduced output. This function is most useful with advanced water balance modelling (chapter \@ref(advancedwaterbalance)).

## Applications {#basicwaterbalanceapplications}

The basic water balance model is easier to parameterize and is faster the advanced water balance model. These features make it appropriate for applications that do not seek a high predictive capacity of water status at the plant level, but require robust estimates of water fluxes at the stand, landscape or regional levels. In our opinion the basic water balance model may be useful for the following applications: 

1. To monitor or forecast temporal variation in transpiration fluxes and soil water content in particular stands or in multiple stands across a landscape or region. 
2. Monitor or forecast temporal variation of plant drought stress in particular stands or in multiple stands across a landscape or region (for example to anticipate mortality events).

For example, @karavani_effect_2018 employed the water balance to provide sound estimates of soil moisture dynamics to predict mushroom production in a network forest stands. The model is particularly interesting to test the relationship between forest structure/composition and the water balance at the stand level or the drought stress suffered by plants, as done in @Ameztegui2017. See also another application in @Rolo2019.
