# Sub-daily atmospheric temperature and radiation variation {#subdailytemplight}

After estimating leaf phenology (chapter \@ref(leafphenologylight)) and simulating the main hydrological processes (chapter \@ref(hydrology)), the advanced water balance model (chapter \@ref(advancedwaterbalance)) starts simulating *subdaily* processes, which include energy balances and photosynthesis/transpiration. In order to properly simulate these processes it is important to consider sub-daily variations in temperature and radiation. Here we detail how sub-daily estimates of above-canopy air temperature and atmospheric incoming radiation are derived from daily input values.

## Above-canopy air temperature

Above-canopy air temperature ($T_{atm}$, in $^\circ C$) diurnal variations are modeled assuming a *sinusoidal pattern* with $T_{atm} = T_{\min}$ at sunrise and $T_{atm} = (T_{\min}+T_{\max})/2$ at sunset. Air temperature varies linearly between sunset and sunrise [@McMurtrie1990]. Sunrise and sunset hours are determined from latitude and sun declination (see [section 4.2 of the reference manual](http://emf-creaf.github.io/meteolandbook/solarradiation.html#day-length) for package **meteoland**).


## Incoming diffuse and direct short-wave radiation {#directdiffuseSWR}
Daily global radiation ($Rad$, in $MJ \cdot m^{-2} \cdot d^{-1}$) is assumed to include both direct and diffuse short-wave radiation (SWR). Using latitude information and whether is a rainy day, this quantity is partitioned into instantaneous direct and diffuse SWR and PAR for different daily substeps. Values of instantaneous direct and diffuse SWR and PAR above the canopy ($I_{beam}$ and $I_{dif}$, in $W \cdot m^{-2}$) are calculated using the methods described in @Spitters1986, which involve comparing daily global radiation with daily potential radiation. All these calculations are performed using routines in package **meteoland** (see details in section [4.6 of the reference manual ](http://emf-creaf.github.io/meteolandbook/solarradiation.html#diurnal-trends-in-diffuse-and-direct-radiation) for this package).

## Incoming long-wave radiation {#longwaveatmradiation}
Once the above-canopy air temperature for a given time step is known, instantaneous long-wave radiation (LWR) coming from the atmosphere ($L_{atm}$, in $W \cdot m^{-2}$) can be calculated following @Campbell1998:
\begin{equation}
L_{atm} = \epsilon_{a} \cdot \sigma \cdot (T_{atm} + 273.16)^{4.0}
\end{equation}
where $T_{atm}$ is air temperature, $\sigma = 5.67 \cdot 10^{-8.0}\,W \cdot K^{-4} \cdot m^{-2}$ is the Stephan-Boltzmann constant and $\epsilon_{a}$ is the emmissivity of the atmosphere, calculated using:
\begin{eqnarray}
\epsilon_{a} &=& (1 - 0.84 \cdot c) \cdot \epsilon_{ac} + 0.84 \cdot c \\
\epsilon_{ac} &=& 1.72 \cdot \left(\frac{e_{atm}}{T_{atm} + 273.16} \right)^{1/7}
\end{eqnarray}
where $e_{atm}$ is the average daily water vapor pressure (in kPa; see \@ref(meteoinput)) and $c$ is the proportion of clouds ($c=1$ in rainy days and $c=0$ otherwise). 