# Carbon pools and components of carbon balance {#carbonpoolsbalance}

## Size of carbon pools {#estimationcarbonpools}

Biomass of leaves, sapwood and fine roots is needed in the model to estimate respiratory costs and the size of the C storage pools. 

### Leaf structural, metabolic and storage biomass

The live leaf area $LA^{live}$ per individual (in $m^2$) is:
\begin{equation}
LA^{live} = 10000 \cdot LAI^{live} / N
(\#eq:leafarea)
\end{equation}
where $N$ is the density of the cohort and $LAI^{live}$ is the leaf area index. Structural leaf biomass per individual ($B_{leaf}$; $g\,dry·ind^{-1}$) is the result of dividing live leaf area by $SLA$ ($m^{2} \cdot kg^{-1}$), the specific leaf area of the species:
\begin{equation}
B_{leaf} = 1000 \cdot LA^{live} / SLA
\end{equation}
where a factor 1000 is used to convert from kg to g. Hence, only expanded leaf area has respiratory cost (i.e. winter resistance buds do not). Leaf storage volume for an individual ($V_{storage,leaf}$; in $L \cdot ind^{-1}$) is:
\begin{equation}
V_{storage, leaf} = LA^{live}  \cdot V_{leaf}
\end{equation}
where $V_{leaf}$ is the water storage capacity of leaf tissue per leaf area unit (in $L\cdot m^{-2}$) (see \@ref(plantwaterstoragecapacity)). Leaf storage volume is necessary to estimate the biomass of metabolic (sugars) or storage (starch) from the concentration of these substances in leaves ($SS_{leaf}$ and $ST_{leaf}$, which are expressed in $mol\,gluc \cdot L^{-1}$), and conversely. For example:
\begin{equation}
B_{sugar,leaf} = SS_{leaf} \cdot V_{storage, leaf} \cdot m_{gluc}
\end{equation}
where $m_{gluc}$ is the molar mass of glucose. To estimate leaf starch storage capacity, the model assumes that up to 10\% of leaf tissue volume can be occupied with starch, so that the leaf starch storage capacity ($ST^{max}_{leaf}$; in $mol \cdot ind^{-1}$) is:
\begin{equation}
ST^{max}_{leaf} = 0.1 \cdot 1000 \cdot \frac{V_{storage, leaf} \cdot \rho_{starch}}{m_{starch}}
\end{equation}

where $\rho_{starch}$ is the density of starch and $m_{starch}$ is its molar mass.

### Sapwood structural, metabolic and storage biomass

Sapwood volume ($V_{sapwood}$; in $L \cdot ind^{-1}$) is defined as the product of sapwood area and the sum of aboveground height and belowground coarse root length:
\begin{equation}
V_{sapwood} = 1000 \cdot SA\cdot (H + \sum_{s}{FRP_s \cdot L_s})
\end{equation}
where $SA$ is sapwood area, $H$ is plant height, $FRP_{s}$ is the proportion of fine roots in soil layer $s$ and $L_{s}$ is the coarse root length in layer $s$ (all lengths expressed here in $m$). Sapwood structural biomass per individual ($B_{sapwood}$; $g\,dry·ind^{-1}$) represents the sapwood biomass of sapwood of trunks, branches and coarse roots. It is defined as the product of $V_{sapwood}$ and wood density  ($\rho_{wood}$; $g dry·cm^{-3}$):
\begin{equation}
B_{sapwood} = 1000 \cdot V_{sapwood} \cdot\rho_{wood}
\end{equation}
While $B_{sapwood}$ represents the structural sapwood biomass, it cannot be used to estimate sapwood respiration, since only xylem axial or radial parenchymatic rays (and not dead cells like tracheids or vessels) contribute to sapwood respiration. Hence, it is useful to estimate sapwood living biomass using:
\begin{equation}
B_{living, sapwood} = 1000 \cdot V_{sapwood} \cdot\rho_{wood} \cdot (1 - f_{conduits})
\end{equation}
where $f_{conduits}$ is the fraction of sapwood volume that corresponds to dead conducts, being the complement of the fraction of parenchymatic tissue. The volume available for metabolic or storage carbon within sapwood is limited by both the sapwood fraction that corresponds to parenchyma and wood porosity (i.e. $(1 - (\rho_{wood}/1.54))$). Sapwood storage volume ($V_{storage, sapwood}$; in $L \cdot ind^{-1}$) is:
\begin{equation}
V_{storage, sapwood} = V_{sapwood} \cdot (1 - (\rho_{wood}/1.54)) \cdot (1 - f_{conduits})
\end{equation}
Analogously to leaf carbon, $V_{storage, sapwood}$ is used to estimate the biomass of metabolic (sugars) or storage (starch) from the concentration of these substances in sapwood ($SS_{sapwood}$ and $ST_{sapwood}$, which are expressed in $mol\,gluc \cdot L^{-1}$), and conversely. For example:
\begin{equation}
B_{sugar,sapwood} = SS_{sapwood} \cdot V_{storage, sapwood} \cdot m_{gluc}
\end{equation}
where $m_{gluc}$ is the molar mass of glucose. To estimate sapwood storage capacity, the model assumes that up to 50\% of volume of parenchymatic cells can be occupied with starch, so that the sapwood starch storage capacity ($ST^{max}_{sapwood}$; in $mol \cdot ind^{-1}$) is:
\begin{equation}
ST^{max}_{sapwood} = 0.5 \cdot 1000 \cdot \frac{V_{storage,sapwood} \cdot \rho_{starch}}{m_{starch}}
\end{equation}

### Fine root structural biomass

The fine root compartment does not have labile carbon (i.e. the model supplies labile carbon for fine roots from sapwood compartment), so that only the structural biomass of fine roots needs to be estimated. If growth is simulated using the basic water balance model, the biomass of fine roots per individual ($B_{fineroot}$; $g\,dry·ind^{-1}$) is assumed half of biomass:
\begin{equation}
B_{fineroot} = B_{leaf}/2
\end{equation}
Hence, in this model fine-root maintenance respiration costs are also influenced by leaf-phenological status [@Sitch2003]. When growth is simulated using the advanced water balance model, fine root length per area in each soil layer ($FLA_s$; $m \cdot m^{-2}$) is estimated from rhizosphere conductance, assuming a cylindrical flow geometry in the rhizosphere. Then fine root biomass per individual ($g\,dry\cdot ind^{-1}$) is calculated using:
\begin{equation}
B_{fineroot} = \sum_{s}{B_{fineroot,s}} = \sum_{s}{\frac{10000\cdot FLA_s}{N\cdot 0.01 \cdot SRL}}
\end{equation}
where $N$ is the density of individuals and $SRL$ ($cm \cdot g\,dry^{-1}$) is the specific root length. One of the model output variables is fine root area in each soil layer ($FRA_s$), which is calculated from $B_{fineroot}$ using:
\begin{equation}
FRA_{s} = 10^{-4}\cdot B_{fineroot,s} \cdot 2.0 \cdot \frac{\pi \cdot SRL}{\rho_{fineroot}}
\end{equation}
where $\rho_{fineroot}$ is fine root tissue density ($g\,dry \cdot cm^{-3}$).

### Total living biomass
Total living biomass per individual (i.e. not accounting for heartwood or xylem conduits) is:
\begin{equation}
B_{total} = B_{leaf} + B_{living, sapwood} + B_{fineroot} + \\
            B_{sugar,leaf} + B_{starch,leaf}+ B_{sugar,sapwood} + B_{starch,sapwood}
\end{equation}
$B_{total}$ is used to express carbon balance components per dry weight of living biomass in the model output, which allows a better comparison across plant cohorts of different size and species.

## Components of carbon balance {#carbonbalancecomponents}

Here we provide the details of carbon balance calculations, i.e. how the components of eqs. \@ref(eq:leafcarbonbalanceequations) and \@ref(eq:sapwoodcarbonbalanceequations) are determined.

### Gross photosynthesis

The soil water balance submodel provides values of photosynthesis calculated at the plant cohort level, but note that the user output of function `spwb` and `pwb` refers to net photosynthesis ($A_n$) after accounting for an estimate of leaf respiration. In the basic water balance model there is no way to make the distinction between gross and net photosynthesis, so we will assume here that $A_g = A_n$ (in $g\,C \cdot m^{-2}$) as calculated in section \@ref(basicphotosynthesis). In the advance water balance model the output is also net photosynthesis, but the distinction is possible (see section \@ref(leafenergybalancephoto)). In any case, here we start with a $A_g$ value in units of carbon per ground area unit, i.e. $g\,C \cdot m^{-2}$, and to enter the carbon balance we need scale photosynthesis to units of glucose per individual ($A$; in $g\,gluc \cdot ind^{-1}$). This is done using:
\begin{equation}
A = \frac{10000 \cdot A_g}{N} \cdot \frac{m_{gluc}}{m_{carbon} \cdot 6}
\end{equation}
where $N$ is the density of individuals per hectare, $m_{gluc}$ is the glucose molar mass and $m_{carbon}$ is the carbon molar mass.

### Maintenance respiration
Maintenance respiration (in $g\,gluc·ind^{-1}$) is calculated for each of the three compartments (leaves, sapwood, and fine roots) individually [@Mouillot2001].  The model uses a $Q_{10}$ relationship with temperature, which means that for every 10 ºC change in temperature there is a $Q_{10}$ factor change in respiration. Baseline maintenance respiration rates per dry biomass ($MR_{leaf}$, $MR_{sapwood}$ and $MR_{fineroot}$ for leaves, parenchymatic sapwood and fine roots, respectively; in $g\,gluc \cdot g\,dry^{-1} \cdot day^{-1}$) are can be specified via control parameters (defaults for all species) or via species-specific parameters and should refer to 20 ºC:
\begin{eqnarray}
M_{leaf} &=& (B_{leaf} + B_{sugar,leaf}) \cdot MR_{leaf} \cdot Q_{10}^{(T_{mean}-20)/10} \\
M_{sapwood} &=& (B_{living,sapwood} + B_{sugar,sapwood}) \cdot MR_{sapwood} \cdot Q_{10}^{(T_{mean}-20)/10} \\
M_{fineroot} &=& B_{fineroot} \cdot MR_{fineroot} \cdot Q_{10}^{(T_{mean}-20)/10} 
\end{eqnarray}
where $T_{mean}$ is the average daily temperature (in ºC). The same equations are used for growth simulations with the basic or advanced water model, the only differences being that in the latter the daily rates are divided by the number of subdaily steps and, hence, subdaily temperature variation is taken into account.

### Growth respiration

Construction costs per unit dry weight of new tissue ($CC_{leaf}$, $CC_{sapwood}$ and $CC_{fineroot}$ for leaves, sapwood and fine roots; in $g\,gluc \cdot g\,dry^{-1}$) are specified as control parameters (i.e. they are not species-specific). These unitary costs include both the carbon used in respiration during growth and structural carbon. Given an increase in leaf area $\Delta LA$, leaf growth respiration is:
\begin{equation}
G_{leaf} = \Delta LA \cdot CC_{leaf} \cdot 1000 / SLA
(\#eq:leafconstructioncost)
\end{equation}
Analogously, given an increase in sapwood area $\Delta LA$, sapwood growth respiration is:
\begin{equation}
G_{sapwood} = \Delta SA \cdot CC_{sapwood} \cdot (H + \sum_{s}{FRP_s \cdot L_s}) \cdot \rho_{wood}
(\#eq:sapwoodconstructioncost)
\end{equation}
Finally, and given an increase in fine root biomass $\Delta B_{fineroot}$:
\begin{equation}
G_{fineroot} = \Delta B_{fineroot} \cdot CC_{fineroot}
\end{equation}

### Phloem transport {#phloemtransport}

When growth is simulated using the basic water balance model, phloem transport between leaf and sapwood ($F_{phloem}$) is simply modelled as the flow needed to make the concentration of metabolic carbon equal in both compartments. When the advanced water balance submodel is used, $F_{phloem}$ is modelled following @Holtta2017. Specifically, the instantaneous phloem flow per leaf area basis ($mol\,gluc\cdot m^{-2} \cdot s^{-1}$) depends on $k_{phloem}$, i.e. the phloem conductance per leaf area basis ($L\cdot m^{-2} \cdot MPa^{-1} \cdot s^{-1}$), sap viscosity relative to water and the difference in turgor between the sieve cells of leaf and sapwood compartments. $k_{phloem}$ is estimated as linear function of stem maximum conductance, $k_{stem,max}$:
\begin{equation}
k_{phloem} = f_{phloem} \cdot k_{stem,\max}
\end{equation}
where factor $f_{phloem}$ is specified by the control parameter `phloemConductanceFactor`. Sap viscosity is calculated following @Forst2002, which takes into account temperature and the average sugar concentration between the two compartments (no phloem flow can occur if temperature is below zero). Turgor in sieve cells of each compartment depends on symplastic water potential and osmotic water potential, with Van't Hoff's equation being used to calculate the osmotic water potential, based on temperature, sugar concentration and the concentration of other solutes (control parameter `nonSugarConcentration`). Note that here leaf or sapwood sugar concentration is modulated to account for the effect of the relative water content of the compartment on osmotic water potential.


### Sugar-starch dynamics {#sugarstarchdynamics}

When growth is simulated using the basic water balance submodel, sugar-starch dynamics ($SC_{leaf}$ and $SC_{sapwood}$) are simply defined as the conversion between metabolic and storage carbon needed to keep the sugar concentration equal to an equilibrium required for metabolic functioning, which is specified by control parameters `equilibriumOsmoticConcentration` (including two values, for leaves and sapwood respectively) and `nonSugarConcentration`. For example, if leaf osmotic equilibrium concentration is 0.8 $mol\,gluc \cdot L^{-1}$ and non-sugar concentration is 0.3 $mol\,gluc \cdot L^{-1}$, the model will simulate sugar-starch dynamics to stabilize sugar concentration in leaves to 0.5 $mol\,gluc \cdot L^{-1}$. A lower equilibrium osmotic concentration is required for sapwood, by default 0.6 $mol\,gluc \cdot L^{-1}$, so that sugar equilibrium concentration is 0.1 $mol\,gluc \cdot L^{-1}$. That lower equilibrium concentrations are required for sapwood than for leaves is necessary to sustain the phloem transport of sugars from leaves towards sapwood.

When growth is simulated using the basic water balance submodel, sugar-starch dynamics are similar to the previous case, in the sense that equilibrium sugar concentrations are sought for leaves and sapwood. However, instantaneous conversion rates are calculated depending on equations regulating starch synthesis (occurring when sugar concentration is higher than the equilibrium concentration) and starch hydrolysis (occurring when sugar concentration is lower than the equilibrium concentration). Synthesis is modelled as a Michaelis-Menten function, whereas hydrolysis rate is simply a linear function of starch concentration. Maximum synthesis rates and hydrolysis linear factors are larger (i.e. faster sugar-starch dynamics) in leaves than sapwood.

### Root exudation

Surplus in leaf or sapwood storage carbon is diverted towards root exudation ($RE_{leaf}$ or $RE_{sapwood}$). Hence, root exudation is not a process competing for metabolic carbon, but only a consequence of plant C storage capacity being surpassed [@Prescott2020]. Root exudation may happen in the model when growth is restricted due to sink limitations but photosynthesis continues and storage carbon levels have attained the storage capacity in the leaf compartment ($ST_{leaf} > ST^{max}_{leaf}$) or the sapwood compartment ($ST_{sapwood} > ST^{max}_{sapwood}$).