# Growth, senescence and mortality

## Growth


### Temperature and turgor sink limitations

Sink limitations due to temperature and turgor effects on growth are modelled following @Cabon2019 and @Cabon2020. These authors suggested equations to model sink limitations on cambium cell division and tracheid expansion, but we apply the same approach for simulating growth of leaves, sapwood and fine roots. Cell relative expansion rate ($r_{cell}$) is central to the approach by Cabon et al. and is defined as the relative time derivative of cell volume:
\begin{equation}
r_{cell} = \frac{dV}{Vdt}
\end{equation}
@Cabon2019 first suggested to model the dependence of $r_{cell}$ on cell turgor using Lockhart's equation:
\begin{equation}
r_{cell}(\Psi, \pi_0) = \phi_{max} \cdot (\Psi - \pi_0  - Y_{P})
\end{equation}
where $\Psi$ is the water potential, $\pi_0$ is the osmotic water potential at full turgor and $Y_P = 0.05$ MPa is the turgor yield threshold. Later, @Cabon2020 suggested to account for both turgor and temperature limitations on $r_{cell}$ using the following expanded equation:
\begin{equation}
r_{cell}(T, \Psi, \pi_0) = \phi_{max} \cdot (\Psi - \pi_0  - Y_{P}) \cdot \frac{f_{met}(T_K)}{f_{met}(288.15)} \cdot{f_{micro}(T, T_{thr})}
(\#eq:cellexpansion)
\end{equation}
where $T$ is temperature, $f_{met}(T_K)$ is a function modulating the effect of temperature $T_K$ in Kelvin, on metabolic rate, and $f_{micro}(T, T_{thr})$ is a sigmoidal function modulating the effect of temperature on microtubule stability, depending on a temperature threshold $T_{thr}$. 
Function  $f_{met}(T_K)$ is defined as: 
\begin{equation}
f_{met}(T_K) = \frac{T_K \cdot \exp \big\{ \frac{\Delta H_A}{R^n \cdot T_K}\big\}}{1 + \exp \big\{ \frac{\Delta S_D}{R^n} \cdot \left(1 - \frac{\Delta H_D}{\Delta S_D \cdot T_K} \right)\big\}}
\end{equation}
where $R^n$ is the ideal gas constant, $\Delta H_A = 87500$ the enthalpy of activation and $\Delta H_D = 333000$ and $\Delta S_D = 1090$ the enthalpy and entropy difference (respectively) between the catalytically active and inactive states of the enzymatic system). 

### Leaf growth

Leaf area increment $\Delta LA$ only occurs when phenological state is *unfolding*, and is defined as the minimum of three values expressing three corresponding constraints:
\begin{equation}
\Delta LA = \min( \Delta LA_{alloc}, \Delta LA_{source}, \Delta LA_{sink})
\end{equation}
First, $\Delta LA_{alloc}$ is the maximum leaf area increment allowed by the leaf area target set by the allocation rule, $LA^{target}$ in comparison with current leaf area $LA^{live}$:
\begin{equation}
\Delta LA_{alloc} = \max(LA^{target} - LA^{live},0)
\end{equation}
Remember that leaf area target is updated during *bud formation* (which occurred the year before in the case of deciduous plants). 

Second, $\Delta LA_{source}$ represents the leaf area increment expected given carbon source limitations and is calculated:
\begin{equation}
\Delta LA_{source} = \frac{\max(SS_{leaf}-SS_{leaf,growth},0)\cdot m_{gluc}\cdot V_{storage,leaf}}{1000 \cdot CC_{leaf} / SLA}
\end{equation}
where $SS_{leaf}$ is the current concentration of metabolic sugar, $SS_{leaf,growth}$ is the minimum concentration required for growth (specified in control vector `minimumSugarForGrowth`), $V_{storage,leaf}$ is the leaf storage volume, $m_{gluc}$ is glucose molar mass and the denominator contains the construction costs per leaf area unit, see eq. \@ref(eq:leafconstructioncost).

Finally, $\Delta LA_{sink}$ represents the leaf area increment expected by taking into account maximum leaf tissue growth rate ($RGR_{leaf, max}$; in $m^2 \cdot cm^{-2} \cdot day^{-1}$) relative to sapwood area $SA$ (in $cm^2$)  and the relative cell expansion rate given $T_{day}$, $\Psi_{symp,leaf}$ and $\pi_{0,leaf}$: 
\begin{equation}
\Delta LA_{sink} = SA \cdot RGR_{leaf, max} \cdot \frac{r_{cell}(T_{day}, \Psi_{leaf}, \pi_{0,leaf})}{r_{cell,max}}
\end{equation}
cell relative expansion rate is divided by the maximum relative cell expansion rate $r_{cell,max} = r_{cell}(25, 0, -2)$ so that $RGR_{leaf, max}$ is attained when sink conditions are optimal. Other parameters for eq. \@ref(eq:cellexpansion) are $\phi_{max} = 0.5$, $Y_{P} = 0.05\,MPa$ and $T_thr = 5$ºC.

### Sapwood growth

Sapwood area increment $\Delta SA$ can only occur if $LA^{live}>0$. Unlike leaf area, it is not explicitly constrained by any allocation rule. However, newly assimilated carbon is preferentially allocated to leaves and fine roots because sapwood growth depends on storage reserves. $\Delta SA$ is defined as the minimum of two values expressing source and sink constraints:
\begin{equation}
\Delta SA = \min(\Delta SA_{source}, \Delta SA_{sink})
\end{equation}
$\Delta SA_{source}$ represents the sapwood area increment expected given carbon source limitations and is calculated using:
\begin{equation}
\Delta SA_{source} = \frac{\max(ST_{sapwood}-SS_{sapwood,growth},0)\cdot m_{gluc}\cdot V_{storage,sapwood}}{CC_{sapwood} \cdot (H + \sum_{s}{FRP_s \cdot L_s}) \cdot \rho_{wood}}
\end{equation}
where $ST_{sapwood}$ is the current starch concentration, $SS_{sapwood,growth}$ is the minimum concentration required for growth (specified in control vector `minimumSugarForGrowth`), $V_{storage,sapwood}$ is the sapwood storage volume, $m_{gluc}$ is glucose molar mass and the denominator contains the construction costs per sapwood area unit, see eq. \@ref(eq:sapwoodconstructioncost).

### Fine root growth

Fine root growth is only modelled when simulating growth with the advanced water balance submodel (when using the basic water balance submodel fine root respiration costs are proportional to leaf respiration costs). 

Fine root biomass increment is modelled for each soil layer separately, and is defined analogously to leaf area increment: 
\begin{equation}
\Delta B_{fineroot} = \min( \Delta B_{fineroot,alloc}, \Delta B_{fineroot,source}, \Delta B_{fineroot,sink})
\end{equation}
First, $\Delta B_{fineroot,alloc}$ is the maximum fine root biomass increment allowed by the biomass target set by the allocation rule, $B_{fineroot,target}$ in comparison with current biomass, $B_{fineroot}$:
\begin{equation}
\Delta B_{fineroot,alloc} = \max(B_{fineroot,target} - B_{fineroot},0)
\end{equation}

Second, $\Delta B_{fineroot,source}$ represents the biomass increment expected given carbon source limitations and is calculated:
\begin{equation}
\Delta B_{fineroot,source} = \frac{\max(SS_{sapwood}-SS_{fineroot,growth},0)\cdot m_{gluc}\cdot V_{storage,sapwood}}{CC_{fineroot}}
\end{equation}
where $SS_{sapwood}$ is the current sapwood concentration of metabolic sugar, $SS_{fineroot,growth}$ is the minimum concentration required for fine root growth (specified in control vector `minimumSugarForGrowth`), $V_{storage,sapwood}$ is the sapwood storage volume, $m_{gluc}$ is glucose molar mass and $CC_{fineroot}$ is the construction costs per fine root biomass unit.

Finally, $\Delta B_{fineroot,sink}$ represents the biomass increment expected by taking into account maximum  tissue growth rate ($RGR_{fineroot, max}$; in $g\,dry \cdot g\,dry^{-1} \cdot day^{-1}$) and the relative cell expansion rate given temperature ($T_{day}$), water potential in the rhizosphere ($\Psi_{rhizo,s}$) and the stem osmotic potential at full turgor($\pi_{0,stem}$): 
\begin{equation}
\Delta B_{fineroot,sink} = B_{fineroot} \cdot RGR_{fineroot, max} \cdot \frac{r_{cell}(T_{day}, \Psi_{rhizo,s}, \pi_{0,stem})}{r_{cell,max}}
\end{equation}
cell relative expansion rate is divided by the maximum relative cell expansion rate $r_{cell,max} = r_{cell}(25, 0, -2)$ so that $RGR_{fineroot, max}$ is attained when sink conditions are optimal. Other parameters for eq. \@ref(eq:cellexpansion) are like for leaf growth, $\phi_{max} = 0.5$, $Y_{P} = 0.05\,MPa$ and $T_thr = 5$ºC.


## Senescence

### Leaf senescence


During drought-periods (i.e. if $f_{turgor}(\Psi_{leaf})=0$) cavitation may occur. However, cavitation is applied at the leaf area level and not at the sapwood area level. During drought periods reductions of live leaf area can come from either sapwood conversion into heartwood or cavitation. First, the model compares the current $\Psi_{leaf}$ value with $\Psi_{\min}$ the minimum potential experienced since drought started:
\begin{equation}
\Psi_{\min} = \min(\Psi_{leaf}, \, \Psi_{\min})
\end{equation}
Then the model determines the proportion of embolized conducts as the complement of hydraulic conductance corresponding to $\Psi_{\min}$, relative to the maximum hydraulic conductance. If the transpiration mode is "Simple", this is done using a whole-plant conductance function:
\begin{equation}
P_{embolism}=1- K(\Psi_{\min}) = \exp \left \{\ln{(0.5)}\cdot \left[ \frac{\Psi_{\min}}{\Psi_{extract}} \right] ^r \right \} 
\end{equation}
where $\Psi_{extract}$ is the potential at which conductance is 50% of maximum and $r=3$. If the transpiration mode is "Complex", $P_{embolism}$ is calculated using the stem-leaves vulnerability curve:
\begin{equation}
P_{emb}= 1- \frac{k_{stem}(\Psi_{\min})}{k_{stem}(0)} = 1 - \exp \left \{-\left[ \frac{\Psi_{\min}}{d_{stem}} \right] ^{c_{stem}} \right \} 
\end{equation}
Since leaf area reduction may also come from sapwood conversion into heartwood, the model determines which process leads to a larger reduction in leaf area:
\begin{equation}
LAI^{live} = \min(LAI^{live} - N \cdot \Delta SA_{turnover} \cdot Hv , \, LAI^{predrought} \cdot (1 - P_{emb}))
\end{equation}
and expanded leaf area ($LAI^{\phi}$) and dead leaf area ($LAI^{dead}$) are modified accordingly. 


### Sapwood senescence

@Prentice1993 assumed a constant annual rate of 4% for the conversion from sapwood to heartwood. Similarly, @Sitch2003 assumed a sapwood annual turnover rate of 5% for all biomes. A reasonable value for maximum daily turnover rate would be (assuming an annual rate 4.5%):
\begin{equation}
1-0.955^{(1/365)} = 0.0001261398
\end{equation}
The actual proportion of sapwood area that is transformed into heartwood is:
\begin{equation}
p_{heartwood} = \frac{0.0001261398}{1+15\cdot e^{-0.01\cdot H}}
\end{equation}
where 0.01 is a constant causing short plants to have slower turnover rates. 

Sapwood turnover is applied at the same rate in evergreen and deciduous species. The amount of sapwood that is converted to heartwood every day, $\Delta SA_{turnover}$, is thus:
\begin{equation}
\Delta SA_{turnover} = SA \cdot p_{heartwood}
\end{equation}

### Fine root senescence

## Update of plant traits and allocation targets

### Plant traits

Several anatomic and physiological parameters are updated every day after applying changes in the size of leaf, sapwood and fine root compartments. Hence, the model allows simulating plastic responses to environmental cues mediated by growth and senescence of plant tissues.

First leaf area index ($LAI^{live}$) is updated from leaf area ($LA^{live}$) inverting eq. \@ref(eq:leafarea). The Huber value ($H_v$, the sapwood area to leaf area ratio; in $m^{2}\cdot m^{-2}$) is affected by changes in $LA^{live}$ and sapwood area $SA$:
\begin{equation}
H_v = \frac{SA/10000}{LA^{live}}
\end{equation}
When simulating growth with the basic water balance model, leaf area index and Huber value are the only traits affected by changes in the size of compartments. It is only when we simulate growth with the advanced water balance model that we get a real sense of plant acclimation. Stem maximum conductance per leaf area unit ($k_{stem, max}$; in $mmol·m^{-2}·s^{-1}·MPa^{-1}$) is modelled as a function of species-specific xylem conductivity ($k_{xylem, max}$; in $kg·m^{-1}·s^{-1}·MPa^{-1}$), leaf area, sapwood area and tree height [@Christoffersen2016]:
\begin{equation}
k_{stem, max} = \frac{1000}{0.018} \cdot \frac{k_{xylem, max} \cdot (SA/10000)}{(H/100) \cdot LA^{live}} \cdot \chi_{taper}
\end{equation}
where $\chi_{taper}$ is a factor to account for taper of xylem conduit with height [@Savage2010; @Christoffersen2016], 0.018 is the molar weight of water (in $kg\cdot mol^{-1}$). Both an increase in $SA$ or a decrease in $LA^{live}$ (i.e. an increase in $H_v$) increase $k_{stem, max}$ and, hence, alleviate drought effects (i.e. a lower decrease in water potential across the stem for the same flow). In contrast, an increase in plant height will decrease stem conductance and increase drought stress. 

Changes in stem maximum conductances have cascade effects on root and rhizosphere conductances. First, coarse root minimum resistance is defined as a fixed proportion of whole-plant minimum resistance, so an increase in stem maximum conductance will increase whole-plant conductance and coarse root conductance, $k_{root,max}$. In turn, rhizosphere minimum resistance (i.e. maximum conductance) is defined as a fraction value of total resistance, when averaged across a range of soil water potential values. An increase in $k_{stem, max}$, will also affect whole-plant conductance, $k_{plant, max}$, and therefore $k_{rhizo,max}$.

The proportion of conductance loss due to cavitation ($PLC_{stem}$) is reduced whenever sapwood area growth occurs (provided control parameter `cavitationRefill = "growth"`):
\begin{equation}
PLC_{stem, t+1} = \min(PLC_{stem,t} - \frac{\Delta SA}{SA},0)
\end{equation}

### Leaf area and fine root biomass targets

Leaf area target ($LA_{target}$) is updated when phenological phase is *bud formation*. If allocation follows a *constant Huber value* strategy, the model tries to keep a constant value $H_{v,target}$, and the leaf area target is defined as: 
\begin{equation}
LA_{target} = \frac{SA}{10000 \cdot H_{v,target}}
\end{equation}
Note that the specification of $LA_{target}$ will cause sapwood area increases to be followed by leaf area increases, as long as $H_{v} > H_{v,target}$. If allocation follows a *constant whole-plant conductance* strategy, the model tries to keep a constant value $k_{plant,target}$, and here the leaf area target is defined as: 
\begin{equation}
LA_{target} = LA^{live} \cdot \frac{k_{plant,max}}{k_{plant,target}}
\end{equation}
In this strategy, increases in leaf area will be scheduled whenever the current whole-plant conductance is above target value (i.e. $k_{plant,max} > k_{plant,target}$).  

While leaf area target depends on the allocation strategy, fine root biomass target ($B_{fineroot,target}$) for any given layer directly follows changes in rhizosphere maximum conductance ($k_{rhizo,max}$). The estimation of fine root biomass also depends on soil saturated conductance, species-specific root length, root length density and density of fine roots.

## Plant mortality thresholds

Plant cohorts can die from either *starvation* (if metabolic carbon is exhausted) or *dessication* (tissue dehydration). When simulating growth with the basic water balance submodel, starvation occurs if $SS_{sapwood} \leq 0$ and, since plant water balance is not explicitly modelled, dessication is determined if $PLC_{stem} \geq 0.5$.  When simulating growth with the advanced water balance submodel, starvation occurs also if $SS_{sapwood} \leq 0$, but in this case a better indicator of dehydration can be used, the stem symplastic relative water content $RWC_{stem, symp}$. Dessication is determined in this case if $RWC_{stem, symp} \leq 0.5$. 
