# (PART) Forest dynamics modelling {-}

# Forest dynamics model {#dynamicsmodelling}

This chapter provides an overview of a forest dynamics model, which builds on the previous models and allows simulating the recruitment, growth and mortality of woody plant cohorts in a forest stand. The model is run using function `fordyn()` for a set of years.

## Design principles

The design of the forest dynamics model is to a large degree inherited from the water balance and growth models it builds on. Readers should refer to former sections to learn the design of the basic water balance (see \@ref(basicdesign)), advanced water/energy balance (see \@ref(advanceddesign)) or growth/mortality processes (see \@ref(growthdesign)). Recruitment is explicitly simulated at the level of `fordyn()` and hence will be the focus of this section. Recruitment of saplings involves a number of processes (flowering and polinisation, fruit/seed production, dispersal, storage, seed predation, germination, seedling establishment and survival until the sapling stage). All these processes have their own biotic and abiotic drivers [@Price2001], so that modelling becomes a challenging task. Processes leading to recruiment are frequently extremely simplified or their mechanisms ignored in many forest models [@Price2001]. The design of the forest dynamics model with respect to recruitment follows that of many gap models. Local seed production is considered in a binary way, where plants are considered fertile and able to produce viable seeds if they reach a given height (different for shrubs and trees). Alternatively, the user can specify a set of species whose seeds arrive to the target stand via dispersal processes. Actual recruitment depends on a set of regeneration *thresholds* are used to determine whether recruitment of new saplings occurs. Typically, regeneration thresholds concern environmental conditions, although some models also consider ungulate browsing [@Werhli2007]. In our case we focus on three environmental drivers limiting the transition from seedlings to saplings: 
  1. Tolerance to low temperatures, indicated by the mean temperature of the coldest month.
  2. Drought tolerance, indicated by the annual moisture index (annual precipitation divided by annual evapotranspiration).
  3. Shade tolerance, indicated by the percentage of photosynthetic active radiation reaching the ground.
A target species will recruit on a given year if current conditions for all three environmental indicators are above the species tolerance thresholds. Recruitment densities and plant size of recruited individuals are specified via species parameters.

## State variables

The main state variables of the forest dynamic model are those conforming the structure and composition of the forest stand, i.e. the set of woody cohorts (either trees or shrubs) and their attributes (height, density, DBH, cover, etc.). Since the model performs calls to the `growth()` model, many other state variables are defined for intra-annual simulations (see \@ref(growthscheduling)).

## Process scheduling

The `fordyn()` model divides the period to be simulated in years, which is the top-level time step of simulations. Given an input `forest` object, the function first initializes the input for function `growth()`. For each year to be simulated the model the performs the following steps:

 1. Calls function `growth()` to simulate daily water/carbon balance, growth and mortality processes (subdaily processes may also be involved in `transpirationMode = "Sperry"`). See section \@ref(growthscheduling) for details of growth scheduling.
 2. Removes plant cohorts whose density (ind. per hectare) is lower than a specified threshold (see control parameter `minimumCohortDensity`).
 3. Simulates recruitment (for species present in the stand or specified via control parameter `seedRain`).
 4. Merges surviving cohorts with recruitment in the `forest` object and prepares the input of function `growth()` for the next annual time step.
 5. Store current status of the `forest` object and update output tables/summaries.

## Inputs and outputs

An important difference between `fordyn()` and the previous simulation functions is that it does not require a specific input object, as in `spwb()`or `growth()` functions. In other words, soil, vegetation, meteorology and control inputs are directly introduced as parameters to the function call to `fordyn()`.

### Soil, vegetation and meteorology

**Soil**

Soil input requirements are the same as for the former models and were fully described in section \@ref(soilinput).

**Vegetation**

Unlike the former models, vegetation input for `fordyn` are objects of the class `forest`, which were described in section \@ref(forestobjects).

**Metereological input**

Weather input data must include variables calculated at the **daily** scale. The variables required by function `fordyn()` depend on the transpiration mode, similarly to the previous simulation model functions. We recommend meteorological input to be generated using package **meteoland** [@DeCaceres2018].

### Vegetation functional parameters

The forest dynamics model requires many functional parameters to be specified for plant cohorts. Some of them depend on whether the basic or advanced water balance is adopted, whereas others are inherited from the growth model. Here we report functional parameters needed in addition to those necessary for the growth model (see \@ref(growthvegetationparameters)). 

All of them concern the simulation of recruitment and are specified in the species parameter table (i.e. `SpParams`).

| Symbol | Units | R  | Description                                  | 
|--------|-------|----| ---------------------------------------------|
| $H_{seed,i}$  | $cm$ | `SeedProductionHeight` | Minimum height for seed production |
| $T_{min,recr,i}$  | $^{\circ} \mathrm{C}$ | `MinTempRecr` |  Minimum average temperature (Celsius) of the coldest month for successful recruitment |
| $MI_{min,recr,i}$  |  | `MinMoistureRecr` |  Minimum value of the moisture index (annual precipitation over annual PET) for successful recruitment |
| $FPAR_{min,recr,i}$  | \% | `MinFPARRecr` | Minimum percentage of PAR at the ground level for successful recruitment |
| $DBH_{recr,i}$  | $cm$  | `RecrTreeDBH` | Recruitment DBH for trees |
| $H_{tree, recr,i}$  | $cm$  | `RecrTreeHeight` | Recruitment height for trees |
| $N_{tree, recr,i}$  | $ind \cdot ha^{-1}$  | `RecrTreeDensity` | Recruitment density for trees |
| $Cover_{shrub, recr,i}$  | %  | `RecrShrubCover` | Recruitment cover for shrubs |
| $H_{shrub, recr,i}$  | $cm$  | `RecrShrubHeight` | Recruitment height for shrubs |
| $Z50_{recr,i}$  | $mm$  | `RecrZ50` | Soil depth corresponding to 50% of fine roots for recruitment |
| $Z95_{recr,i}$  | $mm$  | `RecrZ95` | Soil depth corresponding to 95% of fine roots for recruitment |

### Control parameters

Control parameters modulate the overall behavior of `fordyn` simulations, which extend the parameters used for growth simulations (see section \@ref(forestgrowthcontrol)). First, there are parameters that regulate the application of recruiment and the removal of cohorts with few individuals:

+ `recruitmentMode [= "deterministic"]`: String describing how recruitment is applied. Current accepted values are "deterministic" or "stochastic".
+ `removeDeadCohorts [= TRUE]`: Boolean flag to indicate the removal of cohorts whose density is too low.
+ `minimumCohortDensity [= 1]`: Threshold of density resulting in cohort removal.

Next, a few parameters control the production of seeds in a qualitative way:

+ `seedRain [= NULL]`: Vector of species codes whose seed rain is to be simulated. If `NULL` the species identity of seed rain is taken from species currently present in the forest stand and with minimum size (see below).
+ `seedProductionTreeHeight [= 300]`: Default minimum tree height for producing seeds (when species parameter `SeedProductionHeight` is missing).
+ `seedProductionShrubHeight [= 30]`: Default minimum shrub height for producing seeds (when species parameter `SeedProductionHeight` is missing).

Then we have default parameters determining whether recruitment occurs:

+ `minTempRecr [= 0]`: Default threshold of minimum average temperature of the coldest month necessary for recruiting (when species parameter `MinTempRecr` is missing).
+ `minMoistureRecr [= 0.3]`: Default threshold of minimum moisture index (annual precipitation over annual ETP) necessary for recruiting (when species parameter `MinMoistureRecr` is missing).
+ `minFPARRecr [= 10]`: Default threshold of minimum fraction of PAR (in %) reaching the ground necessary for recruiting (when species parameter `MinFPARRecr` is missing).

Finally, there are a set of parameters specifying default values for recruited cohort attributes:

+ `recrTreeDBH [= 1]`: Default DBH (cm) for recruited trees (when species parameter `RecrTreeDBH` is missing).
+ `recrTreeDensity [= 100]`: Default density (ind·ha-1) for recruited trees (when species parameter `RecrTreeDensity` is missing).
+ `recrTreeHeight [= 100]`: Default height (cm) for recruited trees (when species parameter `RecrTreeHeight` is missing).
+ `recrShrubCover [= 1]`: Default cover (%) for recruited shrubs (when species parameter `RecrShrubCover` is missing).
+ `recrShrubHeight [= 100]`: Default height (cm) for recruited shrubs (when species parameter `RecrShrubHeight` is missing).
+ `recrTreeZ50 [= 100]`: Default value for Z50 (mm) in recruited trees (when species parameter `RecrZ50` is missing).
+ `recrShrubZ50 [= 50]`: Default value for Z50 (mm) in recruited shrubs (when species parameter `RecrZ50` is missing).
+ `recrTreeZ95 [= 1000]`: Default value for Z95 (mm) in recruited trees (when species parameter `RecrZ50` is missing).
+ `recrShrubZ50 [= 500]`: Default value for Z95 (mm) in recruited shrubs (when species parameter `RecrZ50` is missing).

### Model output {#forestdynamicsoutput}


| Element | Description                                                |
|---------|------------------------------------------------------------|
| `StandSummary`| A data frame with stand-level summaries (leaf area index, tree basal area, tree density, shrub cover, etc.) at the beginning of the simulation and after each simulated year. |
| `SpeciesSummary`| A data frame with species-level summaries (leaf area index, tree basal area, tree density, shrub cover, etc.) at the beginning of the simulation and after each simulated year. |
| `CohortSummary`| A data frame with cohort-level summaries (leaf area index, tree basal area, tree density, shrub cover, etc.) at the beginning of the simulation and after each simulated year. |
| `TreeTable`| A data frame with tree-cohort data (species, density, diameter, height, etc.) at the beginning of the simulation (if any) and after each simulated year. |
| `DeadTreeTable`| A data frame with dead tree-cohort data (species, density, diameter, height, etc.) at the beginning of the simulation and after each simulated year. |
| `ShrubTable`| A data frame with shrub-cohort data (species, density, cover, height, etc.) at the beginning of the simulation and after each simulated year. |
| `DeadShrubTable`| A data frame with dead shrub-cohort data (species, density, cover, height, etc.) at the beginning of the simulation (if any) and after each simulated year. |
| `ForestStructures`| A list with the `forest` object of the stand at the beginning of the simulation and after each simulated year. |
| `GrowthResults`| A list with the results of calling function `growth` (i.e., see \@ref(forestgrowthoutput)) for each simulated year. |

## Process details

TO BE WRITTEN