# Water balance post-simulation procedures



## Live fuel moisture content

Pressure-volume curves are useful to determine the moisture content of live fuel elements (leaves and twigs). Given an average relative water content of a water compartment, its live fuel moisture content ($LFMC$ in $g H_2O \cdot g^{-1}$ of dry tissue) can be calculated using:
\begin{equation}
LFMC = RWC \cdot \Theta \cdot \frac{\rho_{H_2O}}{\rho} = RWC \cdot LFMC_{max}
\end{equation}
where $\Theta$ is the tissue porosity ($cm^3$ of water per $cm^3$ of tissue), $\rho$ is the density of the tissue and $\rho_{H_2O}$ is the density of water.

If we know $RWC_{apo}(\Psi_{apo})$, the relative water content in conduits, and $V_{segment}$ (in $m^3$), the volume of conducting tissue (sapwood) in the segment, then the mass of water that is stored in conduits is: 
\begin{equation}
S_{apo}(\Psi_{apo}) = V_{segment} \cdot f_{apo} \cdot RWC_{apo}(\Psi_{apo}) \cdot \rho_{w}
\end{equation}
where $\rho_{w}$ is the density of water ($kgH_2O \cdot m^{-3}$) and $f_{apo,s}$ is the volume fraction of apoplastic tissue within sapwood. Similarly, the amount of water stored in the symplastic tissue of the segment at any time is:
\begin{equation}
S_{sym}(\Psi_{sym}) = V_{segment} \cdot (1 - f_{apo}) \cdot RWC_{sym}(\Psi_{sym}) \cdot \rho_{w}
\end{equation}

Finally, if we consider that both apoplastic and symplastic tissues are at the same water potential, the water content in the segment will be:
\begin{equation}
S(\Psi) = V_{segment} \cdot (f_{apo} \cdot RWC_{apo}(\Psi) + (1 - f_{apo}) \cdot RWC_{sym}(\Psi)) \cdot \rho_{w}
\end{equation}

## Water use efficiency
