
# Symbols

The following tables list all symbols used in this document, along with their units and definition. When symbols are input for **medfate** model functions, the R name of those parameters in the package (either in data frame `SpParamsMED`, soil input data frame, or the output of functions such as `spwbInput()`) is also indicated. 

## Dimensions
| Symbol | Units | R | Description                        |
|--------|-------|---------|------------------------------------|
| $\Delta t_{step}$ | $s$ | `86400/ndailysteps` | Subdaily temporal step | 
| $\Delta t_{substep}$ | $s$ | `86400/(ndailysteps*nsubsteps)` | Subdaily temporal substep | 
| $c$ | (count) | | Number of plant cohorts |
| $l$ | (count) | | Number of vertical layers |
| $\Delta z$ | $m$ | `verticalLayerSize/100` | Width of vertical layers |
| $S$    | (count) | | Number of soil layers |
| $d_{s}$ | $mm$ | `widths` | Width of soil layer $s$ |
| $Z_{s}$ | $mm$ | `widths` | Depth of soil layer $s$ |
| $Z_{soil}$ | $mm$ |  | Overall soil depth |


## Soils

| Symbol | Units | R | Description                        |
|--------|-------|---------|------------------------------------|
| $P_{clay,s}$ | % | `clay`|  Percent of clay in soil layer $s$ |
| $P_{sand,s}$ | % | `sand` | Percent of sand in soil layer $s$ |
| $OM_s$ | % | `om` | Percentage of organic mater per dry weight in soil layer $s$|
| $BD_{s}$ | $g\cdot cm^{-3}$ | `bd` | Bulk density in soil layer $s$ |
| $P_{rocks,s}$ | % | `rfc` | Percentage of rock fragment content in soil layer $s$ |
| $\theta_s$ | $m^3 \cdot m^{-3}$ | | Volumetric moisture in soil layer $s$ |
| $\Psi_s$ | MPa | | Water potential in soil layer $s$ |
| $\Psi_{fc}$ | MPa | | Water potential at field capacity |
| $A_s$, $B_s$ | | | Parameters of the Saxton pedotransfer functions for soil layer $s$|
| $\theta_{sat, s}$ |$m^3 \cdot m^{-3}$ | `VG_theta_sat`| Volumetric moisture at saturation for soil layer $s$|
| $\theta_{fc, s}$ |$m^3 \cdot m^{-3}$ |  | Volumetric moisture at field capacity (-0.033 MPa) for soil layer $s$ |
| $\theta_{wp,s}$ |$m^3 \cdot m^{-3}$ |  | Volumetric moisture at wilting point (-1.5 MPa) for soil layer $s$ |
| $\theta_{res,s}$ |$m^3 \cdot m^{-3}$ | `VG_theta_res` | Residual volumetric moisture for soil layer $s$ |
| $n_s$ | | `VG_n` | Parameter $n$ of the Van Genuchten [-@Genuchten1980] model for soil layer $s$ |
| $\alpha_s$ | | `VG_alpha`| Parameter $\alpha$ of the Van Genuchten [-@Genuchten1980] model for soil layer $s$ |
| $K_{sat,s}$ | $mmol \cdot s^{-1} \cdot m^{-1} \cdot MPa^{-1}$ | `Ksat` | Saturated soil conductivity for soil layer $s$.|
| $K_{drain}$ | $mm \cdot d^{-1}$ | `Kdrain` | Hydraulic conductivity for deep drainage. |
| $P_{macro, s}$ | % | `macro` | Percentage of macroporosity corresponding to soil layer $s$. |
| $\gamma_{soil}$ | $mm \cdot day^{-1}$ | `Gsoil` | The maximum daily evaporation from soil |
| $\kappa_{soil}$ | (unitless) | `Ksoil` | Extinction parameter to regulate the amount of water evaporated from each soil layer |
| $Z_{wt}$ | $mm$ | | Water table depth |
| $V_{s}$ | $mm$ | | Water volume in soil layer $s$ |
| $V_{soil}$ | $mm$ | | Overall water volume in the soil |
| $V_{fc, soil}$ | $mm$ | | Water retention capacity of the whole soil |
| $W_{s}$ | [0-1] |`W` | Proportion of moisture in relation to field capacity in soil layer $s$ |
| $W_{i,s}$ | [0-1] |`W` | Proportion of moisture in relation to field capacity in soil layer $s$ within fraction of stand area covered by cohort $i$ |
| $W_{rhizo, i,s}$ | [0-1] | | Proportion of moisture in relation to field capacity in soil layer $s$ within the rhizosphere of cohort $i$ |
| $S_{snow}$ | $mm$ |`SWE` | Snow water equivalent of the snow pack storage over the soil surface |


## Vegetation

| Symbol | Units | R | Description                        |
|--------|-------|---------|------------------------------------|
| $SP_i$  | (count) | `Species` | Species identity of cohort $i$ |
| $A_{sh,i}$  | $cm^2$ |  | Area occupied by an average shrub individual of cohort $i$ |
| $B_{sh,i}$  | $kg$ |  | Fine-fuel biomass of an average shrub individual of cohort $i$ |
| $H_i$  | $cm$  | `Height` | Average tree or shrub height of cohort $i$ |
| $H_{crown,i}$ | $cm$ | | Crown base height (i.e. the height corresponding to the first living branch) of cohort $i$ |
| $CCF_i$ | | | Crown competition factor of cohort $i$ |
| $CW_i$ | $m$ | | Crown width that a tree of cohort $i$ would have in open-ground conditions |
| $CR_i$ | [0-1] | `CR`| Crown ratio (i.e. ratio between crown length and plant height) of cohort $i$ |
| $N_i$ | $ind · ha^{-1}$ | `N` | Density of tree individuals of cohort $i$ |
| $DBH_i$ | $cm$ | `DBH` | Diameter at breast height of trees in cohort $i$ |
| $Cover_i$ | % | `Cover` | Percent cover of shrubs in cohort $i$ |
| $FB_{i}$ | $kg \cdot m^{-2}$ | | Foliar biomass of cohort $i$ |
| $FB_{tree,i}$ | $kg$ | | Foliar biomass of a single tree of cohort $i$ |
| $\phi_i$ | [0-1] | | Fraction of maximum leaf area currently expanded for cohort $i$ |
| $LAI^{live}_i$ | $m^2 \cdot m^{-2}$ | `LAI_live` | (Maximum) leaf area index (one-side leaf area per surface area of the stand) of cohort $i$ |
| $LAI^{dead}_i$ | $m^2 \cdot m^{-2}$ | `LAI_dead` | Dead leaf area index (one-side dead leaf area per surface area of the stand) of cohort $i$ |
| $LAI^{\phi}_i$ | $m^2 \cdot m^{-2}$ | `LAI_expanded` | Current expanded leaf area index (one-side expanded leaf area per surface area of the stand) of cohort $i$ |
| $LAI^{all}_{i}$ | $m^2 \cdot m^{-2}$ | | Total leaf area index (live or dead) of cohort $i$ |
| $LAI^{live}_{stand}$ | $m^2 \cdot m^{-2}$ | | Maximum leaf area index of living leaves of the stand |
| $LAI^{dead}_{stand}$ | $m^2 \cdot m^{-2}$ | | Leaf area index of dead leaves of the stand |
| $LAI^{\phi}_{stand}$ | $m^2 \cdot m^{-2}$ | | Current expanded leaf area index of live leaves of the stand |
| $LAI_{stand}$ | $m^2 \cdot m^{-2}$ | | Total leaf area index (live or dead) of the stand |
| $LA_{i}$ | $m^{2}$ | | Leaf area of an individual of cohort $i$ |
| $FRP_{i,s}$ | [0-1] | `V[i,s]` | The proportion of fine roots of cohort $i$ in soil layer $s$ |
| $FRA_{i,s}$ | $m^2$ | | Fine root area of cohort $i$ in soil layer $s$ |
| $L_{radial,i,s}$ | m | | Radial length of coarse roots of cohort $i$ in soil layer $s$ |
| $W_{i}$ | $kg \cdot m^{-2}$ | | Fine fuel biomass of cohort $i$ |
| $Z_{50,i}$ | mm | `Z50` | Depth above which 50% of the fine root mass of cohort $i$ is located |
| $Z_{95,i}$ | mm | `Z95` | Depth above which 95% of the fine root mass of cohort $i$ is located |


## Meteorology


| Symbol | Units | R | Description                        |
|--------|-------|---------|------------------------------------|
| $DOY$ | | `DOY`| Day of the year |
| $T_{mean}$ | $^{\circ} \mathrm{C}$ | `MeanTemperature` | Mean daily temperature |
| $T_{min}$ | $^{\circ} \mathrm{C}$ | `MinTemperature` | Minimum daily temperature |
| $T_{max}$ | $^{\circ} \mathrm{C}$ | `MaxTemperature` | Maximum daily temperature |
| $T_{base}$ | $^{\circ} \mathrm{C}$ |  | Base temperature for calculation of $GDD$ |
| $RH_{min}$ | % | `MinRelativeHumidity` | Minimum daily relative humidity |
| $RH_{max}$ | % | `MaxRelativeHumidity` | Maximum daily relative humidity |
| $P$ | $L \cdot m^{-2} = mm$ | `Precipitation` | Precipitation (including rainfall and snow) |
| $Pr$ | $L \cdot m^{-2} = mm$ | `Rainfall` | Liquid water precipitation (rainfall) |
| $Ps$ | $L \cdot m^{-2} = mm$ | `Snow` | Snow precipitation |
| $PET$ | $L \cdot m^{-2} = mm$ | `PET` | Potential evapotranspiration, preferably calculated using Penman's equation |
| $Rad$ | $MJ \cdot m^{-2}$ | `Radiation` | Solar radiation after accounting for clouds |
| $u$ | $m \cdot s^{-1}$ | `WindSpeed` | Wind speed |
| $P_{atm}$ | kPa |  | Atmospheric pressure |
| $\rho_{air}$ | $kg \cdot m^{-3}$ |  | Air density |
| $T_{atm}$ | $^{\circ} \mathrm{C}$ |  `Tatm` | Atmospheric (above-canopy) air temperature |
| $T_{can}$ | $^\circ \mathrm{C}$ | `Tcan` | Canopy air temperature |
| $T_{air,j}$ | $^\circ \mathrm{C}$ | `Tair` | Air temperature in canopy layer $j$ |
| $T_{soil,s}$ | $^\circ \mathrm{C}$ | `Tsoil.s` | Temperature of soil layer $s$ |
| $e_{atm}$ | kPa | | Atmospheric  (above-canopy) water vapor pressure |
| $e_{air,j}$ | kPa | `VPair` | Water vapor pressure in canopy layer $j$ |
| $C_{atm}$ | kPa | `Catm` | Atmospheric  (above-canopy) $CO_2$ concentration |
| $C_{air,j}$ | kPa | `VPair` | $CO_2$ concentration in canopy layer $j$ |
| $u_j$ | $m \cdot s^{-1}$ |  | Wind speed at canopy layer $j$ |

## Anatomy 

| Symbol | Units | R | Description                        |
|--------|-------|---------|------------------------------------|
| $H_v$  | $m^2 \cdot m^{-2}$ | `1/Al2As` | Huber value (ratio of sapwood area to leaf area) |
|  $LW$   | $cm$  | `LeafWidth` | Leaf width |
| $SLA$  | $m^2 \cdot kg^{-1}$ | `SLA` | Specific leaf area |
| $\rho_{leaf}$ | $g \cdot cm^{-3}$ | `LeafDensity` | Leaf tissue density |
| $\rho_{wood}$ | $g \cdot cm^{-3}$ | `WoodDensity` | Wood tissue density |
| $\rho_{fineroot}$ | $g \cdot cm^{-3}$ | `FineRootDensity` | Fine root tissue density |
| $\Theta_{sapwood}$ | $m^3 \cdot m^{-3}$ | | Sapwood porosity (volume of empty spaces over total volume) |
| $\Theta_{leaf}$ | $m^3 \cdot m^{-3}$ | | Leaf porosity (volume of empty spaces over total volume) |
| $SRL$ | $cm \cdot g^{-1}$ | `SRL` | Specific root length |
| $RLD$ | $cm \cdot cm^{-3}$ | `RLD` | Fine root length density (i.e. density of root length per soil volume) |
| $r_{6.35}$ | | `r635` | Ratio between the weight of leaves plus branches and the weight of leaves alone for branches of 6.35 mm |

## Radiation

| Symbol | Units | R | Description                        |
|--------|-------|---------|------------------------------------|
| $k_{PAR,i}$ | (unitless) | `kPAR` | PAR extinction coefficient for cohort $i$ |
| $k_{SWR,i}$ | (unitless) |  | SWR extinction coefficient for cohort $i$ |
| $k_{LWR}$ | (unitless) |  | LWR extinction coefficient |
| $k_{b}$ | (unitless) | | Extinction coefficient for direct light  for cohort $i$|
| $k_{d,i}$ | (unitless) | | Extinction coefficient for diffuse light for cohort $i$ (equal to $k_{PAR,i}$ or $k_{SWR,i}$) |
| $\alpha_{SWR,i}$ | [0-1] | `alphaSWR` | Short-wave radiation absorbance coefficient  for cohort $i$|
| $\alpha_{PAR,i}$ | [0-1] | | PAR absorbance coefficient  for cohort $i$|
| $\gamma_{SWR,i}$ | [0-1] |`gammaSWR` | Short-wave radiation leaf reflectance (albedo) for cohort $i$ |
| $\gamma_{SWR,soil}$ | [0-1] | | Short-wave radiation soil reflectance |
| $\gamma_{PAR,i}$ | [0-1] | | PAR leaf reflectance for cohort $i$ |
| $L^{PAR}_{ground}$ | [0-1] | `LgroundPAR` | Fraction of PAR reaching the ground |
| $L^{SWR}_{ground}$ | [0-1] | `LgroundSWR` | Fraction of SWR reaching the ground |
| $I_{beam}$ | $W·m^{-2}$ | | Instantaneous direct shortwave irrradiance from the atmosphere |
| $I_{dif}$ | $W·m^{-2}$ | | Instantaneous diffuse shortwave irrradiance from the atmosphere |
| $L_{atm}$ | $W·m^{-2}$ | | Instantaneous longwave radiation from the atmosphere |
| $I_{beam,j}$ | $W·m^{-2}$ | | Instantaneous direct shortwave irrradiance at the top of canopy layer $j$ |
| $I_{dif,j}$ | $W·m^{-2}$ | | Instantaneous diffuse shortwave irrradiance at the top of canopy layer $j$ |
| $I_{beam,soil}$ | $W·m^{-2}$ | | Instantaneous direct shortwave irrradiance reaching the soil |
| $I_{dif,soil}$ | $W·m^{-2}$ | | Instantaneous diffuse shortwave irrradiance reaching the soil |
| $LAI^{sunlit}_{i,j}$ | $m^2·m^{-2}$ | | Leaf area index of sunlit leaves of cohort $i$ in layer $j$.|
| $LAI^{shade}_{i,j}$ | $m^2·m^{-2}$ | | Leaf area index of shade leaves of cohort $i$ in layer $j$.|
| $\Phi^{sunlit}_{i,j}$ | $W·m^{-2}$ | | Short-wave radiation absorbed by sunlit leaves of cohort $i$ in layer $j$, per leaf area unit.|
| $\Phi^{shade}_{i,j}$ | $W·m^{-2}$ | | Short-wave radiation absorbed by sunlit leaves of cohort $i$ in layer $j$, per leaf area unit.|
| $K^{sunlit}_{abs,i,j}$ | $W·m^{-2}$ | | Short-wave radiation absorbed by sunlit foliage of cohort $i$ in layer $j$, per ground area unit.|
| $K^{shade}_{abs,i,j}$ | $W·m^{-2}$ | | Short-wave radiation absorbed by sunlit foliage of cohort $i$ in layer $j$, per ground area unit.|


## Water balance

| Symbol | Units | R | Description                        |
|--------|-------|---------|------------------------------------|
| $Ps$ | $mm$ | `Snow`| Precipitation as snow |
| $Pr$ | $mm$ | `Rain`| Precipitation as rainfall |
| $Sm$ | $mm$ | `Snowmelt` | Snowmelt |
| $Pr_{net}$ | $mm$ | `NetRain`| Net rainfall |
| $In$ | $mm$ | `Interception` | Interception loss |
| $Ru$ | $mm$ | `Runoff` | Water exported from the stand as runoff |
| $Ro$ | $mm$ | `Runon` | Water imported to the stand as runon |
| $Dd$ | $mm$ | `DeepDrainage` | Water exported from the stand as deep drainage |
| $Es$ | $mm$ | `SoilEvaporation` | Evaporation from the soil surface |
| $Tr$ | $mm$ | `PlantTranspiration`| Plant transpiration |
| $Tr_{i}$ | $mm$ | | Transpiration of plant cohort $i$|

## Energy balance

| Symbol | Units | R | Description                        |
|--------|-------|---------|------------------------------------|
| $K_{abs,can}$ | $W \cdot m^{-2}$ | `SWRcan` |  Atmosphere shortwave radiation absorbed by the canopy |
| $K_{abs,j}$ | $W \cdot m^{-2}$ | |  Atmosphere shortwave radiation absorbed by canopy layer $j$ |
| $K_{abs,soil}$ | $W \cdot m^{-2}$ | `SWRsoil`  |  Atmosphere shortwave radiation absorbed by the soil |
| $L_{net,can}$ | $W \cdot m^{-2}$ | `LWRcan`  |  Canopy net longwave radiation |
| $L_{net,j}$ | $W \cdot m^{-2}$ | |  Net long-wave radiation of canopy layer $j$ |
| $L_{net,soil}$ | $W \cdot m^{-2}$ | `LWRsoil` |  Soil net longwave radiation |
| $H_{can,atm}$ | $W \cdot m^{-2}$ | `Hcan` |  Turbulent heat exchange between the canopy and the atmosphere |
| $H_{can,soil}$ | $W \cdot m^{-2}$ | `Hcansoil` |  Turbulent heat exchange between the canopy and the soil |
| $H_{j}$ | $W \cdot m^{-2}$ | | Sensible heat flux between canopy layer $j$ and the leaves it contains |
| $LE_{can}$ | $W \cdot m^{-2}$ | `LEcan`| Energy released as latent heat from the canopy towards the atmosphere |
| $LE_{j}$ | $W \cdot m^{-2}$ | | Energy released as latent heat by canopy layer $j$ |
| $LE_{soil}$ | $W \cdot m^{-2}$ | `LEsoil` | Energy released as latent heat from the soil |
| $TC_{LAI}$ | $J \cdot m^{-2} \cdot K^{-1}$ | `thermalcapacityLAI` | Canopy thermal capacitance per LAI unit |
| $TC_{can}$ | $J \cdot m^{-2} \cdot K^{-1}$ | | Canopy thermal capacitance |
| $TC_{j}$ | $J \cdot m^{-2} \cdot K^{-1}$ | | Thermal capacitance of canopy layer $j$ |
| $TC_{soil,s}$ | $J \cdot m^{-2} \cdot K^{-1}$ | | Thermal capacitance of soil layer $s$ |
| $VHC_{soil,s}$ | $J \cdot m^{-3} \cdot K^{-1}$ | | Volumetric heat capacity of soil in layer $s$|

## Forest hydrology

| Symbol | Units | R | Description                        |
|--------|-------|---------|------------------------------------|
| $P_G$ | $mm$ | | Amount of rainfall needed to saturate the canopy for a given event |
| $S_{canopy}$ | $mm$ | `Cm` | Canopy water storage capacity |
| $ER_{ratio}$ | (unitless) |  | Ratio between evaporation rate and rainfall rate |  
| $C_{canopy}$ | [0-1] | | Canopy cover | 
| $PE_{soil}$ | $mm$ | | Evaporation demand from the soil |
| $SE_{soil}$ | $mm$ | | Evaporation supply from the soil |
| $t_{soil}$ | $day$ | | Time needed to evaporate the current water deficit in the first soil layer |

## Plant hydraulics

| Symbol | Units | R | Description                        |
|--------|-------|---------|------------------------------------|
| $K_{stem,max,ref}$ | $kg \cdot s^{-1} \cdot m^{-1} \cdot MPa^{-1}$ | `Kmax_stemxylem` | Maximum stem sapwood reference conductivity per leaf area unit |
| $K_{root,max,ref}$ | $kg \cdot s^{-1} \cdot m^{-1} \cdot MPa^{-1}$ | `Kmax_rootxylem` | Maximum root sapwood reference conductivity per leaf area unit |
| $k_{stem, \max}$ | $mmol \cdot s^{-1} \cdot m^{-2} \cdot MPa^{-1}$ |  `VCstem_kmax` | Maximum whole-stem conductance (per leaf area unit) |
| $k_{root, \max}$ | $mmol \cdot s^{-1} \cdot m^{-2} \cdot MPa^{-1}$ |  `VCroot_kmax` | Maximum root conductance (per leaf area unit) |
| $k_{rhizo, \max}$ | $mmol \cdot s^{-1} \cdot m^{-2} \cdot MPa^{-1}$ |  | Maximum rhizosphere conductance (per leaf area unit) |
| $k_{leaf, \max}$ | $mmol \cdot s^{-1} \cdot m^{-2} \cdot MPa^{-1}$ | `VCleaf_kmax` | Maximum leaf conductance (per leaf area unit) |
| $c_{leaf}$, $d_{leaf}$ | (unitless), MPa | `VCleaf_c`, `VCleaf_d` | Parameters of the vulnerability curve for leaves |
| $c_{root}$, $d_{root}$ | (unitless), MPa | `VCroot_c`, `VCroot_d` | Parameters of the vulnerability curve for root xylem |
| $c_{stem}$, $d_{stem}$ | (unitless), MPa | `VCstem_c`, `VCstem_d` | Parameters of the vulnerability curve for stem xylem |
| $\Psi$ | MPa | | Water potential in a given water compartment/segment |
| $\Psi_P$ | MPa | | Turgor water potential in a given water compartment/segment |
| $\Psi_S$ | MPa | | Osmotic (solute) water potential in a given water compartment |
| $\Psi_{cav}$ | MPa | | Minimum water potential experienced by xylem in previous steps (cavitation) |
| $\Psi_{canopy}$ | MPa | | Canopy water potential |
| $\Psi_{leaf}$ | MPa | | Leaf water potential |
| $\Psi_{rootcrown}$ | MPa | | Water potential at the root crown |
| $\Psi_{stem}$ | MPa | | Water potential at the end (highest part) of the stem |
| $PLC$ | [0-1] | | Proportion of conductance loss |
| $PLC_{stem}$ | [0-1] | | Proportion of conductance loss in stem xylem tissue |
| $p_{root}$ | [0-1] | `pRootDisc` | Relative root conductance leading to hydraulic disconnection from a soil layer |
| $E_i$ | $mmol \cdot s^{-1} \cdot m^{-2}$ | | Steady-state water flow through a hydraulic segment $i$ |
| $k_i$ | $mmol \cdot s^{-1} \cdot m^{-2} \cdot MPa^{-1}$ | | Hydraulic conductance function for segment $i$ |
| $\Psi_{up}$ | MPa | | Upstream water potential |
| $\Psi_{down}$ | MPa | | Downstream water potential |

## Photosynthesis

| Symbol | Units | R | Description                        |
|--------|-------|---------|------------------------------------|
| $J_{max}$ | $\mu mol\,e \cdot m^{-2} \cdot s^{-1}$ | `Jmax` | Maximum rate of electron transport at current leaf temperature |
| $V_{max, 298}$ | $\mu mol\, CO_2 \cdot s^{-1} \cdot m^{-2}$ | `Vmax` | Rubisco's maximum carboxylation rate at current leaf temperature |
| $J_{max, 298}$ | $\mu mol\,e \cdot m^{-2} \cdot s^{-1}$ | `Jmax298` | Maximum rate of electron transport at 298K |
| $V_{max, 298}$ | $\mu mol\, CO_2 \cdot s^{-1} \cdot m^{-2}$ | `Vmax298` | Rubisco's maximum carboxylation rate at 298K |
| $T_{leaf}$ | $^\circ C$| | Leaf temperature. |
| $u_{leaf}$ | $m \cdot s^{-1}$| | Leaf-level wind speed. |
| $VPD_{leaf}$ | kPa | | Leaf vapour pressure deficit. |
| $g_{w}$ | $mol\, H_2O \cdot s^{-1} \cdot m^{-2}$ | | Leaf diffusive conductance to water vapor |
| $g_{c}$ | $mol\, CO_2 \cdot s^{-1} \cdot m^{-2}$ |  | Leaf diffusive conductance to carbon dioxide |
| $g_{sw}$ | $mol\, H_2O \cdot s^{-1} \cdot m^{-2}$ | | Leaf stomatal conductance to water vapour |
| $g_{sw,\min}$ | $mol\, H_2O \cdot s^{-1} \cdot m^{-2}$ | `Gswmin` | Minimum stomatal conductance to water vapour |
| $g_{sw,\max}$ | $mol\, H_2O \cdot s^{-1} \cdot m^{-2}$ | `Gswmax` | Maximum stomatal conductance to water vapour |
| $\Phi^{leaf}_{PAR}$ | $W \cdot m^{-2}$ | | Photosynthetically active radiation absorbed per leaf area |
| $Q^{leaf}_{PAR}$ | $\mu mol\,photon \cdot m^{-2} \cdot s^{-1}$ | | PAR photon flux density per leaf area |
| $A_c$ | $\mu mol\, CO_2 \cdot s^{-1} \cdot m^{-2}$ | | Rubisco-limited photosynthesis rate |
| $A_e$ | $\mu mol\, CO_2 \cdot s^{-1} \cdot m^{-2}$ | | Electron transport-limited photosynthesis rate |
| $A$ | $\mu mol\, CO_2 \cdot s^{-1} \cdot m^{-2}$ | | Leaf gross photosynthesis rate |
| $A_n$ | $\mu mol\, CO_2 \cdot s^{-1} \cdot m^{-2}$ | | Leaf net photosynthesis rate |

## Plant water content

| Symbol | Units | R | Description                        |
|--------|-------|---------|------------------------------------|
| $\epsilon_{leaf}$ | MPa | `LeafEPS` | Modulus of elasticity of leaves |
| $\epsilon_{stem}$ | MPa | `StemEPS` | Modulus of elasticity of symplastic xylem tissue |
| $\pi_{0,leaf}$ | MPa | `LeafPI0` | Osmotic potential at full turgor of leaves |
| $\pi_{0,stem}$ | MPa | `StemPI0` | Osmotic potential at full turgor of symplastic xylem tissue |
| $RWC$ | [0-1] | | Relative water content |
| $RWC_{sym}$ | [0-1] | | Relative water content in the symplasm fraction of a tissue |
| $RWC_{apo}$ | [0-1] | | Relative water content in the apoplasm fraction of a tissue |
| $V_{segment}$ | $l \cdot m^{-2}$ | | Water capacity of a segment (leaf or stem) |
| $V_{leaf}$ | $l \cdot m^{-2}$ | `Vleaf` | Leaf water capacity per leaf area unit |
| $V_{sapwood}$ | $l \cdot m^{-2}$ | `Vsapwood` | Sapwood water capacity per leaf area unit |

## Stomatal regulation

| Symbol | Units | R | Description                        |
|--------|-------|---------|------------------------------------|
| $\theta_1(\Psi_{leaf})$, $\theta_2(\Psi_{leaf})$  | [0-1] | | Cost functions 1 and 2 |
| $\beta(\Psi_{leaf})$  | [0-1] | | Gain function |
| $Profit_1(\Psi_{leaf})$, $Profit_2(\Psi_{leaf})$  | [0-1] | | Profit functions 1 and 2 |
| $E_{sunlit}$ | $mmol \cdot s^{-1} \cdot m^{-2}$ | | Instantaneous transpiration flow rate for sunlit leaves |
| $E_{shade}$ | $mmol \cdot s^{-1} \cdot m^{-2}$ | | Instantaneous transpiration flow rate for shade leaves |

## Carbon pools

| Symbol | Units | R | Description                        |
|--------|-------|---------|------------------------------------|
| $V_{storage,leaf, i}$ | $L \cdot ind^{-1}$ | | Leaf (carbon) storage volume for an individual of cohort $i$ |
| $V_{storage,sapwood, i}$ | $L \cdot ind^{-1}$ | | Sapwood (carbon) storage volume for an individual of cohort $i$ |
| $SS_{leaf,i}$  | $mol\,gluc\cdot L^{-1}$ | `SugarLeaf` | Sugar concentration in leaves of cohort $i$ |
| $SS_{sapwood,i}$  | $mol\,gluc\cdot L^{-1}$ |  `SugarSapwood` | Sugar concentration in sapwood of cohort $i$ |
| $ST_{leaf,i}$  | $mol\,gluc\cdot L^{-1}$ |  `StarchLeaf` | Starch concentration in leaves of cohort $i$ |
| $ST_{sapwood,i}$  | $mol\,gluc\cdot L^{-1}$ |  `StarchSapwood` | Starch concentration in sapwood of cohort $i$ |
| $S_{plant}$  | $mol\,gluc\cdot ind^{-1}$ | | Total labile carbon storage in a plant individual |
| $B_{leaf}$  | $g\,dry\cdot ind^{-1}$ | | Leaf dry biomass in a plant individual (for respiration costs) |
| $B_{sapwood}$  | $g\,dry\cdot ind^{-1}$ | | Sapwood dry biomass in a plant individual |
| $B_{living, sapwood}$  | $g\,dry\cdot ind^{-1}$ | | Sapwood dry biomass corresponding to (living) parenchymatic tissues in a plant individual (for respiration costs) |
| $B_{fineroot}$  | $g\,dry\cdot ind^{-1}$ | | Fine root dry biomass in a plant individual (for respiration costs) |

## Carbon balance

| Symbol | Units | R | Description                        |
|--------|-------|---------|------------------------------------|
| $M_{leaf}$  | $mol\,gluc\cdot day^{-1}$ | | Leaf daily maintenance respiration in a plant individual |
| $M_{sapwood}$  | $mol\,gluc\cdot day^{-1}$ | | Sapwood daily maintenance respiration in a plant individual |
| $M_{fineroot}$  | $mol\,gluc\cdot day^{-1}$ | | Fine root daily maintenance respiration in a plant individual |
| $MR_{leaf}$ | $g\,gluc\cdot g\,dry^{-1}\cdot day^{-1}$ | `RERleaf` | Leaf respiration rate at 20 ºC |
| $MR_{sapwood}$ | $g\,gluc\cdot g\,dry^{-1}\cdot day^{-1}$ | `RERsapwood` | Living sapwood (parenchymatic tissue) respiration rate at 20 ºC |
| $MR_{fineroot}$ | $g\,gluc\cdot g\,dry^{-1}\cdot day^{-1}$ | `RERfineroot` | Fine root respiration rate at 20 ºC |
| $G_{leaf}$  | $mol\,gluc\cdot day^{-1}$ | | Leaf daily growth respiration in a plant individual |
| $G_{sapwood}$  | $mol\,gluc\cdot day^{-1}$ | | Sapwood daily growth respiration in a plant individual |
| $G_{fineroot}$  | $mol\,gluc\cdot day^{-1}$ | | Fine root daily growth respiration in a plant individual |
| $F_{phloem}$  | $mol\,gluc\cdot day^{-1}$ | | Daily phloem transport of sugars from leaves to sapwood |
| $SC_{leaf}$  | $mol\,gluc\cdot day^{-1}$ | | Daily conversion from leaf sugar to leaf starch |
| $SC_{sapwood}$  | $mol\,gluc\cdot day^{-1}$ | | Daily conversion from sapwood sugar to sapwood starch |
| $TS_{leaf}$  | $mol\,gluc\cdot day^{-1}$ | | Daily translocation of leaf sugars (prior to senescence) |
| $TS_{sapwood}$  | $mol\,gluc\cdot day^{-1}$ | | Daily translocation of sapwood sugars (prior to senescence) |
| $TT_{leaf}$  | $mol\,gluc\cdot day^{-1}$ | | Daily translocation of leaf starch (prior to senescence) |
| $RE_{leaf}$  | $mol\,gluc\cdot day^{-1}$ | | Daily root exudation of leaf carbon |
| $RE_{sapwood}$  | $mol\,gluc\cdot day^{-1}$ | | Daily root exudation of sapwood carbon |

## Growth, senescence and mortality

| Symbol | Units | R | Description                        |
|--------|-------|---------|------------------------------------|
| $RGR_{leaf, max}$ | $m^2 \cdot cm^{-2} \cdot day^{-1}$| `RGRleafmax` | Maximum leaf area daily growth rate, relative to sapwood area |
| $RGR_{sapwood, max}$ | $cm^2 \cdot cm^{-2} \cdot day^{-1}$| `RGRsapwoodmax` | Maximum daily sapwood relative growth rate (in sapwood area basis) |
| $RGR_{fineroot, max}$ | $g\,dry \cdot g\,dry^{-1} \cdot day^{-1}$| `RGRfinerootmax` | Maximum daily fine root relative growth rate |
| $LA^{target}$ | $m^2$ | | Leaf area allocation target |
| $\Delta LA_{alloc}$ | $m^2$ | | Leaf area increase dictated by the difference between leaf area allocation target and current leaf area |
| $\Delta LA_{source}$ | $m^2$ | | Leaf area increase according to leaf metabolic carbon availability |
| $\Delta LA_{sink}$ | $m^2$ | | Leaf area increase dictated by sink limitations (leaf relative growth rate and relative cell expansion rate)  |
| $\Delta LA$ | $m^2$ | | Actual leaf area increase  |
| $\Delta SA_{source}$ | $cm^2$ | | Sapwood area increase according to sapwood storage carbon availability |
| $\Delta SA_{sink}$ | $cm^2$ | | Sapwood area increase dictated by sink limitations |
| $\Delta SA$ | $cm^2$ | | Actual sapwood area increase  |
| $B_{fineroot,target}$ | $g\, dry$ | | Fine root biomass allocation target |
| $\Delta B_{fineroot,alloc}$ | $g\, dry$ | | Fine root biomass increase dictated by the difference between fine root biomass allocation target and current fine root biomass |
| $\Delta B_{fineroot,source}$ | $g\, dry$ | | Fine root biomass increase according to sapwood metabolic carbon availability |
| $\Delta B_{fineroot,sink}$ | $g\, dry$ | | Fine root biomass increase dictated by sink limitations (fine root relative growth rate and relative cell expansion rate)  |
| $\Delta B_{fineroot}$ | $g\, dry$ | | Actual fine root biomass increase  |